// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/team"
	"github.com/Wei-Shaw/sub2api/ent/teamtransaction"
)

// TeamTransactionCreate is the builder for creating a TeamTransaction entity.
type TeamTransactionCreate struct {
	config
	mutation *TeamTransactionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTeamID sets the "team_id" field.
func (_c *TeamTransactionCreate) SetTeamID(v int64) *TeamTransactionCreate {
	_c.mutation.SetTeamID(v)
	return _c
}

// SetOperatorID sets the "operator_id" field.
func (_c *TeamTransactionCreate) SetOperatorID(v int64) *TeamTransactionCreate {
	_c.mutation.SetOperatorID(v)
	return _c
}

// SetMemberID sets the "member_id" field.
func (_c *TeamTransactionCreate) SetMemberID(v int64) *TeamTransactionCreate {
	_c.mutation.SetMemberID(v)
	return _c
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (_c *TeamTransactionCreate) SetNillableMemberID(v *int64) *TeamTransactionCreate {
	if v != nil {
		_c.SetMemberID(*v)
	}
	return _c
}

// SetAction sets the "action" field.
func (_c *TeamTransactionCreate) SetAction(v string) *TeamTransactionCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *TeamTransactionCreate) SetAmount(v float64) *TeamTransactionCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_c *TeamTransactionCreate) SetNillableAmount(v *float64) *TeamTransactionCreate {
	if v != nil {
		_c.SetAmount(*v)
	}
	return _c
}

// SetOwnerBalanceBefore sets the "owner_balance_before" field.
func (_c *TeamTransactionCreate) SetOwnerBalanceBefore(v float64) *TeamTransactionCreate {
	_c.mutation.SetOwnerBalanceBefore(v)
	return _c
}

// SetNillableOwnerBalanceBefore sets the "owner_balance_before" field if the given value is not nil.
func (_c *TeamTransactionCreate) SetNillableOwnerBalanceBefore(v *float64) *TeamTransactionCreate {
	if v != nil {
		_c.SetOwnerBalanceBefore(*v)
	}
	return _c
}

// SetOwnerBalanceAfter sets the "owner_balance_after" field.
func (_c *TeamTransactionCreate) SetOwnerBalanceAfter(v float64) *TeamTransactionCreate {
	_c.mutation.SetOwnerBalanceAfter(v)
	return _c
}

// SetNillableOwnerBalanceAfter sets the "owner_balance_after" field if the given value is not nil.
func (_c *TeamTransactionCreate) SetNillableOwnerBalanceAfter(v *float64) *TeamTransactionCreate {
	if v != nil {
		_c.SetOwnerBalanceAfter(*v)
	}
	return _c
}

// SetMemberBalanceBefore sets the "member_balance_before" field.
func (_c *TeamTransactionCreate) SetMemberBalanceBefore(v float64) *TeamTransactionCreate {
	_c.mutation.SetMemberBalanceBefore(v)
	return _c
}

// SetNillableMemberBalanceBefore sets the "member_balance_before" field if the given value is not nil.
func (_c *TeamTransactionCreate) SetNillableMemberBalanceBefore(v *float64) *TeamTransactionCreate {
	if v != nil {
		_c.SetMemberBalanceBefore(*v)
	}
	return _c
}

// SetMemberBalanceAfter sets the "member_balance_after" field.
func (_c *TeamTransactionCreate) SetMemberBalanceAfter(v float64) *TeamTransactionCreate {
	_c.mutation.SetMemberBalanceAfter(v)
	return _c
}

// SetNillableMemberBalanceAfter sets the "member_balance_after" field if the given value is not nil.
func (_c *TeamTransactionCreate) SetNillableMemberBalanceAfter(v *float64) *TeamTransactionCreate {
	if v != nil {
		_c.SetMemberBalanceAfter(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *TeamTransactionCreate) SetNote(v string) *TeamTransactionCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *TeamTransactionCreate) SetNillableNote(v *string) *TeamTransactionCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TeamTransactionCreate) SetCreatedAt(v time.Time) *TeamTransactionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TeamTransactionCreate) SetNillableCreatedAt(v *time.Time) *TeamTransactionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetTeam sets the "team" edge to the Team entity.
func (_c *TeamTransactionCreate) SetTeam(v *Team) *TeamTransactionCreate {
	return _c.SetTeamID(v.ID)
}

// Mutation returns the TeamTransactionMutation object of the builder.
func (_c *TeamTransactionCreate) Mutation() *TeamTransactionMutation {
	return _c.mutation
}

// Save creates the TeamTransaction in the database.
func (_c *TeamTransactionCreate) Save(ctx context.Context) (*TeamTransaction, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TeamTransactionCreate) SaveX(ctx context.Context) *TeamTransaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamTransactionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamTransactionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TeamTransactionCreate) defaults() {
	if _, ok := _c.mutation.Amount(); !ok {
		v := teamtransaction.DefaultAmount
		_c.mutation.SetAmount(v)
	}
	if _, ok := _c.mutation.OwnerBalanceBefore(); !ok {
		v := teamtransaction.DefaultOwnerBalanceBefore
		_c.mutation.SetOwnerBalanceBefore(v)
	}
	if _, ok := _c.mutation.OwnerBalanceAfter(); !ok {
		v := teamtransaction.DefaultOwnerBalanceAfter
		_c.mutation.SetOwnerBalanceAfter(v)
	}
	if _, ok := _c.mutation.Note(); !ok {
		v := teamtransaction.DefaultNote
		_c.mutation.SetNote(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := teamtransaction.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TeamTransactionCreate) check() error {
	if _, ok := _c.mutation.TeamID(); !ok {
		return &ValidationError{Name: "team_id", err: errors.New(`ent: missing required field "TeamTransaction.team_id"`)}
	}
	if _, ok := _c.mutation.OperatorID(); !ok {
		return &ValidationError{Name: "operator_id", err: errors.New(`ent: missing required field "TeamTransaction.operator_id"`)}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "TeamTransaction.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := teamtransaction.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "TeamTransaction.action": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "TeamTransaction.amount"`)}
	}
	if _, ok := _c.mutation.OwnerBalanceBefore(); !ok {
		return &ValidationError{Name: "owner_balance_before", err: errors.New(`ent: missing required field "TeamTransaction.owner_balance_before"`)}
	}
	if _, ok := _c.mutation.OwnerBalanceAfter(); !ok {
		return &ValidationError{Name: "owner_balance_after", err: errors.New(`ent: missing required field "TeamTransaction.owner_balance_after"`)}
	}
	if _, ok := _c.mutation.Note(); !ok {
		return &ValidationError{Name: "note", err: errors.New(`ent: missing required field "TeamTransaction.note"`)}
	}
	if v, ok := _c.mutation.Note(); ok {
		if err := teamtransaction.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "TeamTransaction.note": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TeamTransaction.created_at"`)}
	}
	if len(_c.mutation.TeamIDs()) == 0 {
		return &ValidationError{Name: "team", err: errors.New(`ent: missing required edge "TeamTransaction.team"`)}
	}
	return nil
}

func (_c *TeamTransactionCreate) sqlSave(ctx context.Context) (*TeamTransaction, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TeamTransactionCreate) createSpec() (*TeamTransaction, *sqlgraph.CreateSpec) {
	var (
		_node = &TeamTransaction{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(teamtransaction.Table, sqlgraph.NewFieldSpec(teamtransaction.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.OperatorID(); ok {
		_spec.SetField(teamtransaction.FieldOperatorID, field.TypeInt64, value)
		_node.OperatorID = value
	}
	if value, ok := _c.mutation.MemberID(); ok {
		_spec.SetField(teamtransaction.FieldMemberID, field.TypeInt64, value)
		_node.MemberID = &value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(teamtransaction.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(teamtransaction.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.OwnerBalanceBefore(); ok {
		_spec.SetField(teamtransaction.FieldOwnerBalanceBefore, field.TypeFloat64, value)
		_node.OwnerBalanceBefore = value
	}
	if value, ok := _c.mutation.OwnerBalanceAfter(); ok {
		_spec.SetField(teamtransaction.FieldOwnerBalanceAfter, field.TypeFloat64, value)
		_node.OwnerBalanceAfter = value
	}
	if value, ok := _c.mutation.MemberBalanceBefore(); ok {
		_spec.SetField(teamtransaction.FieldMemberBalanceBefore, field.TypeFloat64, value)
		_node.MemberBalanceBefore = &value
	}
	if value, ok := _c.mutation.MemberBalanceAfter(); ok {
		_spec.SetField(teamtransaction.FieldMemberBalanceAfter, field.TypeFloat64, value)
		_node.MemberBalanceAfter = &value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(teamtransaction.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(teamtransaction.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamtransaction.TeamTable,
			Columns: []string{teamtransaction.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TeamID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamTransaction.Create().
//		SetTeamID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamTransactionUpsert) {
//			SetTeamID(v+v).
//		}).
//		Exec(ctx)
func (_c *TeamTransactionCreate) OnConflict(opts ...sql.ConflictOption) *TeamTransactionUpsertOne {
	_c.conflict = opts
	return &TeamTransactionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamTransaction.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TeamTransactionCreate) OnConflictColumns(columns ...string) *TeamTransactionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TeamTransactionUpsertOne{
		create: _c,
	}
}

type (
	// TeamTransactionUpsertOne is the builder for "upsert"-ing
	//  one TeamTransaction node.
	TeamTransactionUpsertOne struct {
		create *TeamTransactionCreate
	}

	// TeamTransactionUpsert is the "OnConflict" setter.
	TeamTransactionUpsert struct {
		*sql.UpdateSet
	}
)

// SetTeamID sets the "team_id" field.
func (u *TeamTransactionUpsert) SetTeamID(v int64) *TeamTransactionUpsert {
	u.Set(teamtransaction.FieldTeamID, v)
	return u
}

// UpdateTeamID sets the "team_id" field to the value that was provided on create.
func (u *TeamTransactionUpsert) UpdateTeamID() *TeamTransactionUpsert {
	u.SetExcluded(teamtransaction.FieldTeamID)
	return u
}

// SetOperatorID sets the "operator_id" field.
func (u *TeamTransactionUpsert) SetOperatorID(v int64) *TeamTransactionUpsert {
	u.Set(teamtransaction.FieldOperatorID, v)
	return u
}

// UpdateOperatorID sets the "operator_id" field to the value that was provided on create.
func (u *TeamTransactionUpsert) UpdateOperatorID() *TeamTransactionUpsert {
	u.SetExcluded(teamtransaction.FieldOperatorID)
	return u
}

// AddOperatorID adds v to the "operator_id" field.
func (u *TeamTransactionUpsert) AddOperatorID(v int64) *TeamTransactionUpsert {
	u.Add(teamtransaction.FieldOperatorID, v)
	return u
}

// SetMemberID sets the "member_id" field.
func (u *TeamTransactionUpsert) SetMemberID(v int64) *TeamTransactionUpsert {
	u.Set(teamtransaction.FieldMemberID, v)
	return u
}

// UpdateMemberID sets the "member_id" field to the value that was provided on create.
func (u *TeamTransactionUpsert) UpdateMemberID() *TeamTransactionUpsert {
	u.SetExcluded(teamtransaction.FieldMemberID)
	return u
}

// AddMemberID adds v to the "member_id" field.
func (u *TeamTransactionUpsert) AddMemberID(v int64) *TeamTransactionUpsert {
	u.Add(teamtransaction.FieldMemberID, v)
	return u
}

// ClearMemberID clears the value of the "member_id" field.
func (u *TeamTransactionUpsert) ClearMemberID() *TeamTransactionUpsert {
	u.SetNull(teamtransaction.FieldMemberID)
	return u
}

// SetAction sets the "action" field.
func (u *TeamTransactionUpsert) SetAction(v string) *TeamTransactionUpsert {
	u.Set(teamtransaction.FieldAction, v)
	return u
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *TeamTransactionUpsert) UpdateAction() *TeamTransactionUpsert {
	u.SetExcluded(teamtransaction.FieldAction)
	return u
}

// SetAmount sets the "amount" field.
func (u *TeamTransactionUpsert) SetAmount(v float64) *TeamTransactionUpsert {
	u.Set(teamtransaction.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *TeamTransactionUpsert) UpdateAmount() *TeamTransactionUpsert {
	u.SetExcluded(teamtransaction.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *TeamTransactionUpsert) AddAmount(v float64) *TeamTransactionUpsert {
	u.Add(teamtransaction.FieldAmount, v)
	return u
}

// SetOwnerBalanceBefore sets the "owner_balance_before" field.
func (u *TeamTransactionUpsert) SetOwnerBalanceBefore(v float64) *TeamTransactionUpsert {
	u.Set(teamtransaction.FieldOwnerBalanceBefore, v)
	return u
}

// UpdateOwnerBalanceBefore sets the "owner_balance_before" field to the value that was provided on create.
func (u *TeamTransactionUpsert) UpdateOwnerBalanceBefore() *TeamTransactionUpsert {
	u.SetExcluded(teamtransaction.FieldOwnerBalanceBefore)
	return u
}

// AddOwnerBalanceBefore adds v to the "owner_balance_before" field.
func (u *TeamTransactionUpsert) AddOwnerBalanceBefore(v float64) *TeamTransactionUpsert {
	u.Add(teamtransaction.FieldOwnerBalanceBefore, v)
	return u
}

// SetOwnerBalanceAfter sets the "owner_balance_after" field.
func (u *TeamTransactionUpsert) SetOwnerBalanceAfter(v float64) *TeamTransactionUpsert {
	u.Set(teamtransaction.FieldOwnerBalanceAfter, v)
	return u
}

// UpdateOwnerBalanceAfter sets the "owner_balance_after" field to the value that was provided on create.
func (u *TeamTransactionUpsert) UpdateOwnerBalanceAfter() *TeamTransactionUpsert {
	u.SetExcluded(teamtransaction.FieldOwnerBalanceAfter)
	return u
}

// AddOwnerBalanceAfter adds v to the "owner_balance_after" field.
func (u *TeamTransactionUpsert) AddOwnerBalanceAfter(v float64) *TeamTransactionUpsert {
	u.Add(teamtransaction.FieldOwnerBalanceAfter, v)
	return u
}

// SetMemberBalanceBefore sets the "member_balance_before" field.
func (u *TeamTransactionUpsert) SetMemberBalanceBefore(v float64) *TeamTransactionUpsert {
	u.Set(teamtransaction.FieldMemberBalanceBefore, v)
	return u
}

// UpdateMemberBalanceBefore sets the "member_balance_before" field to the value that was provided on create.
func (u *TeamTransactionUpsert) UpdateMemberBalanceBefore() *TeamTransactionUpsert {
	u.SetExcluded(teamtransaction.FieldMemberBalanceBefore)
	return u
}

// AddMemberBalanceBefore adds v to the "member_balance_before" field.
func (u *TeamTransactionUpsert) AddMemberBalanceBefore(v float64) *TeamTransactionUpsert {
	u.Add(teamtransaction.FieldMemberBalanceBefore, v)
	return u
}

// ClearMemberBalanceBefore clears the value of the "member_balance_before" field.
func (u *TeamTransactionUpsert) ClearMemberBalanceBefore() *TeamTransactionUpsert {
	u.SetNull(teamtransaction.FieldMemberBalanceBefore)
	return u
}

// SetMemberBalanceAfter sets the "member_balance_after" field.
func (u *TeamTransactionUpsert) SetMemberBalanceAfter(v float64) *TeamTransactionUpsert {
	u.Set(teamtransaction.FieldMemberBalanceAfter, v)
	return u
}

// UpdateMemberBalanceAfter sets the "member_balance_after" field to the value that was provided on create.
func (u *TeamTransactionUpsert) UpdateMemberBalanceAfter() *TeamTransactionUpsert {
	u.SetExcluded(teamtransaction.FieldMemberBalanceAfter)
	return u
}

// AddMemberBalanceAfter adds v to the "member_balance_after" field.
func (u *TeamTransactionUpsert) AddMemberBalanceAfter(v float64) *TeamTransactionUpsert {
	u.Add(teamtransaction.FieldMemberBalanceAfter, v)
	return u
}

// ClearMemberBalanceAfter clears the value of the "member_balance_after" field.
func (u *TeamTransactionUpsert) ClearMemberBalanceAfter() *TeamTransactionUpsert {
	u.SetNull(teamtransaction.FieldMemberBalanceAfter)
	return u
}

// SetNote sets the "note" field.
func (u *TeamTransactionUpsert) SetNote(v string) *TeamTransactionUpsert {
	u.Set(teamtransaction.FieldNote, v)
	return u
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *TeamTransactionUpsert) UpdateNote() *TeamTransactionUpsert {
	u.SetExcluded(teamtransaction.FieldNote)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TeamTransaction.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamTransactionUpsertOne) UpdateNewValues() *TeamTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(teamtransaction.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamTransaction.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TeamTransactionUpsertOne) Ignore() *TeamTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamTransactionUpsertOne) DoNothing() *TeamTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamTransactionCreate.OnConflict
// documentation for more info.
func (u *TeamTransactionUpsertOne) Update(set func(*TeamTransactionUpsert)) *TeamTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamTransactionUpsert{UpdateSet: update})
	}))
	return u
}

// SetTeamID sets the "team_id" field.
func (u *TeamTransactionUpsertOne) SetTeamID(v int64) *TeamTransactionUpsertOne {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.SetTeamID(v)
	})
}

// UpdateTeamID sets the "team_id" field to the value that was provided on create.
func (u *TeamTransactionUpsertOne) UpdateTeamID() *TeamTransactionUpsertOne {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.UpdateTeamID()
	})
}

// SetOperatorID sets the "operator_id" field.
func (u *TeamTransactionUpsertOne) SetOperatorID(v int64) *TeamTransactionUpsertOne {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.SetOperatorID(v)
	})
}

// AddOperatorID adds v to the "operator_id" field.
func (u *TeamTransactionUpsertOne) AddOperatorID(v int64) *TeamTransactionUpsertOne {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.AddOperatorID(v)
	})
}

// UpdateOperatorID sets the "operator_id" field to the value that was provided on create.
func (u *TeamTransactionUpsertOne) UpdateOperatorID() *TeamTransactionUpsertOne {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.UpdateOperatorID()
	})
}

// SetMemberID sets the "member_id" field.
func (u *TeamTransactionUpsertOne) SetMemberID(v int64) *TeamTransactionUpsertOne {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.SetMemberID(v)
	})
}

// AddMemberID adds v to the "member_id" field.
func (u *TeamTransactionUpsertOne) AddMemberID(v int64) *TeamTransactionUpsertOne {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.AddMemberID(v)
	})
}

// UpdateMemberID sets the "member_id" field to the value that was provided on create.
func (u *TeamTransactionUpsertOne) UpdateMemberID() *TeamTransactionUpsertOne {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.UpdateMemberID()
	})
}

// ClearMemberID clears the value of the "member_id" field.
func (u *TeamTransactionUpsertOne) ClearMemberID() *TeamTransactionUpsertOne {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.ClearMemberID()
	})
}

// SetAction sets the "action" field.
func (u *TeamTransactionUpsertOne) SetAction(v string) *TeamTransactionUpsertOne {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *TeamTransactionUpsertOne) UpdateAction() *TeamTransactionUpsertOne {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.UpdateAction()
	})
}

// SetAmount sets the "amount" field.
func (u *TeamTransactionUpsertOne) SetAmount(v float64) *TeamTransactionUpsertOne {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *TeamTransactionUpsertOne) AddAmount(v float64) *TeamTransactionUpsertOne {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *TeamTransactionUpsertOne) UpdateAmount() *TeamTransactionUpsertOne {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.UpdateAmount()
	})
}

// SetOwnerBalanceBefore sets the "owner_balance_before" field.
func (u *TeamTransactionUpsertOne) SetOwnerBalanceBefore(v float64) *TeamTransactionUpsertOne {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.SetOwnerBalanceBefore(v)
	})
}

// AddOwnerBalanceBefore adds v to the "owner_balance_before" field.
func (u *TeamTransactionUpsertOne) AddOwnerBalanceBefore(v float64) *TeamTransactionUpsertOne {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.AddOwnerBalanceBefore(v)
	})
}

// UpdateOwnerBalanceBefore sets the "owner_balance_before" field to the value that was provided on create.
func (u *TeamTransactionUpsertOne) UpdateOwnerBalanceBefore() *TeamTransactionUpsertOne {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.UpdateOwnerBalanceBefore()
	})
}

// SetOwnerBalanceAfter sets the "owner_balance_after" field.
func (u *TeamTransactionUpsertOne) SetOwnerBalanceAfter(v float64) *TeamTransactionUpsertOne {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.SetOwnerBalanceAfter(v)
	})
}

// AddOwnerBalanceAfter adds v to the "owner_balance_after" field.
func (u *TeamTransactionUpsertOne) AddOwnerBalanceAfter(v float64) *TeamTransactionUpsertOne {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.AddOwnerBalanceAfter(v)
	})
}

// UpdateOwnerBalanceAfter sets the "owner_balance_after" field to the value that was provided on create.
func (u *TeamTransactionUpsertOne) UpdateOwnerBalanceAfter() *TeamTransactionUpsertOne {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.UpdateOwnerBalanceAfter()
	})
}

// SetMemberBalanceBefore sets the "member_balance_before" field.
func (u *TeamTransactionUpsertOne) SetMemberBalanceBefore(v float64) *TeamTransactionUpsertOne {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.SetMemberBalanceBefore(v)
	})
}

// AddMemberBalanceBefore adds v to the "member_balance_before" field.
func (u *TeamTransactionUpsertOne) AddMemberBalanceBefore(v float64) *TeamTransactionUpsertOne {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.AddMemberBalanceBefore(v)
	})
}

// UpdateMemberBalanceBefore sets the "member_balance_before" field to the value that was provided on create.
func (u *TeamTransactionUpsertOne) UpdateMemberBalanceBefore() *TeamTransactionUpsertOne {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.UpdateMemberBalanceBefore()
	})
}

// ClearMemberBalanceBefore clears the value of the "member_balance_before" field.
func (u *TeamTransactionUpsertOne) ClearMemberBalanceBefore() *TeamTransactionUpsertOne {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.ClearMemberBalanceBefore()
	})
}

// SetMemberBalanceAfter sets the "member_balance_after" field.
func (u *TeamTransactionUpsertOne) SetMemberBalanceAfter(v float64) *TeamTransactionUpsertOne {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.SetMemberBalanceAfter(v)
	})
}

// AddMemberBalanceAfter adds v to the "member_balance_after" field.
func (u *TeamTransactionUpsertOne) AddMemberBalanceAfter(v float64) *TeamTransactionUpsertOne {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.AddMemberBalanceAfter(v)
	})
}

// UpdateMemberBalanceAfter sets the "member_balance_after" field to the value that was provided on create.
func (u *TeamTransactionUpsertOne) UpdateMemberBalanceAfter() *TeamTransactionUpsertOne {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.UpdateMemberBalanceAfter()
	})
}

// ClearMemberBalanceAfter clears the value of the "member_balance_after" field.
func (u *TeamTransactionUpsertOne) ClearMemberBalanceAfter() *TeamTransactionUpsertOne {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.ClearMemberBalanceAfter()
	})
}

// SetNote sets the "note" field.
func (u *TeamTransactionUpsertOne) SetNote(v string) *TeamTransactionUpsertOne {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *TeamTransactionUpsertOne) UpdateNote() *TeamTransactionUpsertOne {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.UpdateNote()
	})
}

// Exec executes the query.
func (u *TeamTransactionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamTransactionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamTransactionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TeamTransactionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TeamTransactionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TeamTransactionCreateBulk is the builder for creating many TeamTransaction entities in bulk.
type TeamTransactionCreateBulk struct {
	config
	err      error
	builders []*TeamTransactionCreate
	conflict []sql.ConflictOption
}

// Save creates the TeamTransaction entities in the database.
func (_c *TeamTransactionCreateBulk) Save(ctx context.Context) ([]*TeamTransaction, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TeamTransaction, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TeamTransactionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TeamTransactionCreateBulk) SaveX(ctx context.Context) []*TeamTransaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamTransactionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamTransactionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamTransaction.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamTransactionUpsert) {
//			SetTeamID(v+v).
//		}).
//		Exec(ctx)
func (_c *TeamTransactionCreateBulk) OnConflict(opts ...sql.ConflictOption) *TeamTransactionUpsertBulk {
	_c.conflict = opts
	return &TeamTransactionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamTransaction.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TeamTransactionCreateBulk) OnConflictColumns(columns ...string) *TeamTransactionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TeamTransactionUpsertBulk{
		create: _c,
	}
}

// TeamTransactionUpsertBulk is the builder for "upsert"-ing
// a bulk of TeamTransaction nodes.
type TeamTransactionUpsertBulk struct {
	create *TeamTransactionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TeamTransaction.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamTransactionUpsertBulk) UpdateNewValues() *TeamTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(teamtransaction.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamTransaction.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TeamTransactionUpsertBulk) Ignore() *TeamTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamTransactionUpsertBulk) DoNothing() *TeamTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamTransactionCreateBulk.OnConflict
// documentation for more info.
func (u *TeamTransactionUpsertBulk) Update(set func(*TeamTransactionUpsert)) *TeamTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamTransactionUpsert{UpdateSet: update})
	}))
	return u
}

// SetTeamID sets the "team_id" field.
func (u *TeamTransactionUpsertBulk) SetTeamID(v int64) *TeamTransactionUpsertBulk {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.SetTeamID(v)
	})
}

// UpdateTeamID sets the "team_id" field to the value that was provided on create.
func (u *TeamTransactionUpsertBulk) UpdateTeamID() *TeamTransactionUpsertBulk {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.UpdateTeamID()
	})
}

// SetOperatorID sets the "operator_id" field.
func (u *TeamTransactionUpsertBulk) SetOperatorID(v int64) *TeamTransactionUpsertBulk {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.SetOperatorID(v)
	})
}

// AddOperatorID adds v to the "operator_id" field.
func (u *TeamTransactionUpsertBulk) AddOperatorID(v int64) *TeamTransactionUpsertBulk {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.AddOperatorID(v)
	})
}

// UpdateOperatorID sets the "operator_id" field to the value that was provided on create.
func (u *TeamTransactionUpsertBulk) UpdateOperatorID() *TeamTransactionUpsertBulk {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.UpdateOperatorID()
	})
}

// SetMemberID sets the "member_id" field.
func (u *TeamTransactionUpsertBulk) SetMemberID(v int64) *TeamTransactionUpsertBulk {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.SetMemberID(v)
	})
}

// AddMemberID adds v to the "member_id" field.
func (u *TeamTransactionUpsertBulk) AddMemberID(v int64) *TeamTransactionUpsertBulk {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.AddMemberID(v)
	})
}

// UpdateMemberID sets the "member_id" field to the value that was provided on create.
func (u *TeamTransactionUpsertBulk) UpdateMemberID() *TeamTransactionUpsertBulk {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.UpdateMemberID()
	})
}

// ClearMemberID clears the value of the "member_id" field.
func (u *TeamTransactionUpsertBulk) ClearMemberID() *TeamTransactionUpsertBulk {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.ClearMemberID()
	})
}

// SetAction sets the "action" field.
func (u *TeamTransactionUpsertBulk) SetAction(v string) *TeamTransactionUpsertBulk {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *TeamTransactionUpsertBulk) UpdateAction() *TeamTransactionUpsertBulk {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.UpdateAction()
	})
}

// SetAmount sets the "amount" field.
func (u *TeamTransactionUpsertBulk) SetAmount(v float64) *TeamTransactionUpsertBulk {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *TeamTransactionUpsertBulk) AddAmount(v float64) *TeamTransactionUpsertBulk {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *TeamTransactionUpsertBulk) UpdateAmount() *TeamTransactionUpsertBulk {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.UpdateAmount()
	})
}

// SetOwnerBalanceBefore sets the "owner_balance_before" field.
func (u *TeamTransactionUpsertBulk) SetOwnerBalanceBefore(v float64) *TeamTransactionUpsertBulk {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.SetOwnerBalanceBefore(v)
	})
}

// AddOwnerBalanceBefore adds v to the "owner_balance_before" field.
func (u *TeamTransactionUpsertBulk) AddOwnerBalanceBefore(v float64) *TeamTransactionUpsertBulk {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.AddOwnerBalanceBefore(v)
	})
}

// UpdateOwnerBalanceBefore sets the "owner_balance_before" field to the value that was provided on create.
func (u *TeamTransactionUpsertBulk) UpdateOwnerBalanceBefore() *TeamTransactionUpsertBulk {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.UpdateOwnerBalanceBefore()
	})
}

// SetOwnerBalanceAfter sets the "owner_balance_after" field.
func (u *TeamTransactionUpsertBulk) SetOwnerBalanceAfter(v float64) *TeamTransactionUpsertBulk {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.SetOwnerBalanceAfter(v)
	})
}

// AddOwnerBalanceAfter adds v to the "owner_balance_after" field.
func (u *TeamTransactionUpsertBulk) AddOwnerBalanceAfter(v float64) *TeamTransactionUpsertBulk {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.AddOwnerBalanceAfter(v)
	})
}

// UpdateOwnerBalanceAfter sets the "owner_balance_after" field to the value that was provided on create.
func (u *TeamTransactionUpsertBulk) UpdateOwnerBalanceAfter() *TeamTransactionUpsertBulk {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.UpdateOwnerBalanceAfter()
	})
}

// SetMemberBalanceBefore sets the "member_balance_before" field.
func (u *TeamTransactionUpsertBulk) SetMemberBalanceBefore(v float64) *TeamTransactionUpsertBulk {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.SetMemberBalanceBefore(v)
	})
}

// AddMemberBalanceBefore adds v to the "member_balance_before" field.
func (u *TeamTransactionUpsertBulk) AddMemberBalanceBefore(v float64) *TeamTransactionUpsertBulk {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.AddMemberBalanceBefore(v)
	})
}

// UpdateMemberBalanceBefore sets the "member_balance_before" field to the value that was provided on create.
func (u *TeamTransactionUpsertBulk) UpdateMemberBalanceBefore() *TeamTransactionUpsertBulk {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.UpdateMemberBalanceBefore()
	})
}

// ClearMemberBalanceBefore clears the value of the "member_balance_before" field.
func (u *TeamTransactionUpsertBulk) ClearMemberBalanceBefore() *TeamTransactionUpsertBulk {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.ClearMemberBalanceBefore()
	})
}

// SetMemberBalanceAfter sets the "member_balance_after" field.
func (u *TeamTransactionUpsertBulk) SetMemberBalanceAfter(v float64) *TeamTransactionUpsertBulk {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.SetMemberBalanceAfter(v)
	})
}

// AddMemberBalanceAfter adds v to the "member_balance_after" field.
func (u *TeamTransactionUpsertBulk) AddMemberBalanceAfter(v float64) *TeamTransactionUpsertBulk {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.AddMemberBalanceAfter(v)
	})
}

// UpdateMemberBalanceAfter sets the "member_balance_after" field to the value that was provided on create.
func (u *TeamTransactionUpsertBulk) UpdateMemberBalanceAfter() *TeamTransactionUpsertBulk {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.UpdateMemberBalanceAfter()
	})
}

// ClearMemberBalanceAfter clears the value of the "member_balance_after" field.
func (u *TeamTransactionUpsertBulk) ClearMemberBalanceAfter() *TeamTransactionUpsertBulk {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.ClearMemberBalanceAfter()
	})
}

// SetNote sets the "note" field.
func (u *TeamTransactionUpsertBulk) SetNote(v string) *TeamTransactionUpsertBulk {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *TeamTransactionUpsertBulk) UpdateNote() *TeamTransactionUpsertBulk {
	return u.Update(func(s *TeamTransactionUpsert) {
		s.UpdateNote()
	})
}

// Exec executes the query.
func (u *TeamTransactionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TeamTransactionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamTransactionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamTransactionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
