// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/team"
	"github.com/Wei-Shaw/sub2api/ent/teamtransaction"
)

// TeamTransactionUpdate is the builder for updating TeamTransaction entities.
type TeamTransactionUpdate struct {
	config
	hooks    []Hook
	mutation *TeamTransactionMutation
}

// Where appends a list predicates to the TeamTransactionUpdate builder.
func (_u *TeamTransactionUpdate) Where(ps ...predicate.TeamTransaction) *TeamTransactionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *TeamTransactionUpdate) SetTeamID(v int64) *TeamTransactionUpdate {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *TeamTransactionUpdate) SetNillableTeamID(v *int64) *TeamTransactionUpdate {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetOperatorID sets the "operator_id" field.
func (_u *TeamTransactionUpdate) SetOperatorID(v int64) *TeamTransactionUpdate {
	_u.mutation.ResetOperatorID()
	_u.mutation.SetOperatorID(v)
	return _u
}

// SetNillableOperatorID sets the "operator_id" field if the given value is not nil.
func (_u *TeamTransactionUpdate) SetNillableOperatorID(v *int64) *TeamTransactionUpdate {
	if v != nil {
		_u.SetOperatorID(*v)
	}
	return _u
}

// AddOperatorID adds value to the "operator_id" field.
func (_u *TeamTransactionUpdate) AddOperatorID(v int64) *TeamTransactionUpdate {
	_u.mutation.AddOperatorID(v)
	return _u
}

// SetMemberID sets the "member_id" field.
func (_u *TeamTransactionUpdate) SetMemberID(v int64) *TeamTransactionUpdate {
	_u.mutation.ResetMemberID()
	_u.mutation.SetMemberID(v)
	return _u
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (_u *TeamTransactionUpdate) SetNillableMemberID(v *int64) *TeamTransactionUpdate {
	if v != nil {
		_u.SetMemberID(*v)
	}
	return _u
}

// AddMemberID adds value to the "member_id" field.
func (_u *TeamTransactionUpdate) AddMemberID(v int64) *TeamTransactionUpdate {
	_u.mutation.AddMemberID(v)
	return _u
}

// ClearMemberID clears the value of the "member_id" field.
func (_u *TeamTransactionUpdate) ClearMemberID() *TeamTransactionUpdate {
	_u.mutation.ClearMemberID()
	return _u
}

// SetAction sets the "action" field.
func (_u *TeamTransactionUpdate) SetAction(v string) *TeamTransactionUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *TeamTransactionUpdate) SetNillableAction(v *string) *TeamTransactionUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *TeamTransactionUpdate) SetAmount(v float64) *TeamTransactionUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *TeamTransactionUpdate) SetNillableAmount(v *float64) *TeamTransactionUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *TeamTransactionUpdate) AddAmount(v float64) *TeamTransactionUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetOwnerBalanceBefore sets the "owner_balance_before" field.
func (_u *TeamTransactionUpdate) SetOwnerBalanceBefore(v float64) *TeamTransactionUpdate {
	_u.mutation.ResetOwnerBalanceBefore()
	_u.mutation.SetOwnerBalanceBefore(v)
	return _u
}

// SetNillableOwnerBalanceBefore sets the "owner_balance_before" field if the given value is not nil.
func (_u *TeamTransactionUpdate) SetNillableOwnerBalanceBefore(v *float64) *TeamTransactionUpdate {
	if v != nil {
		_u.SetOwnerBalanceBefore(*v)
	}
	return _u
}

// AddOwnerBalanceBefore adds value to the "owner_balance_before" field.
func (_u *TeamTransactionUpdate) AddOwnerBalanceBefore(v float64) *TeamTransactionUpdate {
	_u.mutation.AddOwnerBalanceBefore(v)
	return _u
}

// SetOwnerBalanceAfter sets the "owner_balance_after" field.
func (_u *TeamTransactionUpdate) SetOwnerBalanceAfter(v float64) *TeamTransactionUpdate {
	_u.mutation.ResetOwnerBalanceAfter()
	_u.mutation.SetOwnerBalanceAfter(v)
	return _u
}

// SetNillableOwnerBalanceAfter sets the "owner_balance_after" field if the given value is not nil.
func (_u *TeamTransactionUpdate) SetNillableOwnerBalanceAfter(v *float64) *TeamTransactionUpdate {
	if v != nil {
		_u.SetOwnerBalanceAfter(*v)
	}
	return _u
}

// AddOwnerBalanceAfter adds value to the "owner_balance_after" field.
func (_u *TeamTransactionUpdate) AddOwnerBalanceAfter(v float64) *TeamTransactionUpdate {
	_u.mutation.AddOwnerBalanceAfter(v)
	return _u
}

// SetMemberBalanceBefore sets the "member_balance_before" field.
func (_u *TeamTransactionUpdate) SetMemberBalanceBefore(v float64) *TeamTransactionUpdate {
	_u.mutation.ResetMemberBalanceBefore()
	_u.mutation.SetMemberBalanceBefore(v)
	return _u
}

// SetNillableMemberBalanceBefore sets the "member_balance_before" field if the given value is not nil.
func (_u *TeamTransactionUpdate) SetNillableMemberBalanceBefore(v *float64) *TeamTransactionUpdate {
	if v != nil {
		_u.SetMemberBalanceBefore(*v)
	}
	return _u
}

// AddMemberBalanceBefore adds value to the "member_balance_before" field.
func (_u *TeamTransactionUpdate) AddMemberBalanceBefore(v float64) *TeamTransactionUpdate {
	_u.mutation.AddMemberBalanceBefore(v)
	return _u
}

// ClearMemberBalanceBefore clears the value of the "member_balance_before" field.
func (_u *TeamTransactionUpdate) ClearMemberBalanceBefore() *TeamTransactionUpdate {
	_u.mutation.ClearMemberBalanceBefore()
	return _u
}

// SetMemberBalanceAfter sets the "member_balance_after" field.
func (_u *TeamTransactionUpdate) SetMemberBalanceAfter(v float64) *TeamTransactionUpdate {
	_u.mutation.ResetMemberBalanceAfter()
	_u.mutation.SetMemberBalanceAfter(v)
	return _u
}

// SetNillableMemberBalanceAfter sets the "member_balance_after" field if the given value is not nil.
func (_u *TeamTransactionUpdate) SetNillableMemberBalanceAfter(v *float64) *TeamTransactionUpdate {
	if v != nil {
		_u.SetMemberBalanceAfter(*v)
	}
	return _u
}

// AddMemberBalanceAfter adds value to the "member_balance_after" field.
func (_u *TeamTransactionUpdate) AddMemberBalanceAfter(v float64) *TeamTransactionUpdate {
	_u.mutation.AddMemberBalanceAfter(v)
	return _u
}

// ClearMemberBalanceAfter clears the value of the "member_balance_after" field.
func (_u *TeamTransactionUpdate) ClearMemberBalanceAfter() *TeamTransactionUpdate {
	_u.mutation.ClearMemberBalanceAfter()
	return _u
}

// SetNote sets the "note" field.
func (_u *TeamTransactionUpdate) SetNote(v string) *TeamTransactionUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *TeamTransactionUpdate) SetNillableNote(v *string) *TeamTransactionUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *TeamTransactionUpdate) SetTeam(v *Team) *TeamTransactionUpdate {
	return _u.SetTeamID(v.ID)
}

// Mutation returns the TeamTransactionMutation object of the builder.
func (_u *TeamTransactionUpdate) Mutation() *TeamTransactionMutation {
	return _u.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *TeamTransactionUpdate) ClearTeam() *TeamTransactionUpdate {
	_u.mutation.ClearTeam()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TeamTransactionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamTransactionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TeamTransactionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamTransactionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamTransactionUpdate) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := teamtransaction.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "TeamTransaction.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Note(); ok {
		if err := teamtransaction.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "TeamTransaction.note": %w`, err)}
		}
	}
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamTransaction.team"`)
	}
	return nil
}

func (_u *TeamTransactionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamtransaction.Table, teamtransaction.Columns, sqlgraph.NewFieldSpec(teamtransaction.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OperatorID(); ok {
		_spec.SetField(teamtransaction.FieldOperatorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperatorID(); ok {
		_spec.AddField(teamtransaction.FieldOperatorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MemberID(); ok {
		_spec.SetField(teamtransaction.FieldMemberID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMemberID(); ok {
		_spec.AddField(teamtransaction.FieldMemberID, field.TypeInt64, value)
	}
	if _u.mutation.MemberIDCleared() {
		_spec.ClearField(teamtransaction.FieldMemberID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(teamtransaction.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(teamtransaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(teamtransaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OwnerBalanceBefore(); ok {
		_spec.SetField(teamtransaction.FieldOwnerBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOwnerBalanceBefore(); ok {
		_spec.AddField(teamtransaction.FieldOwnerBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OwnerBalanceAfter(); ok {
		_spec.SetField(teamtransaction.FieldOwnerBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOwnerBalanceAfter(); ok {
		_spec.AddField(teamtransaction.FieldOwnerBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MemberBalanceBefore(); ok {
		_spec.SetField(teamtransaction.FieldMemberBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMemberBalanceBefore(); ok {
		_spec.AddField(teamtransaction.FieldMemberBalanceBefore, field.TypeFloat64, value)
	}
	if _u.mutation.MemberBalanceBeforeCleared() {
		_spec.ClearField(teamtransaction.FieldMemberBalanceBefore, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MemberBalanceAfter(); ok {
		_spec.SetField(teamtransaction.FieldMemberBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMemberBalanceAfter(); ok {
		_spec.AddField(teamtransaction.FieldMemberBalanceAfter, field.TypeFloat64, value)
	}
	if _u.mutation.MemberBalanceAfterCleared() {
		_spec.ClearField(teamtransaction.FieldMemberBalanceAfter, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(teamtransaction.FieldNote, field.TypeString, value)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamtransaction.TeamTable,
			Columns: []string{teamtransaction.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamtransaction.TeamTable,
			Columns: []string{teamtransaction.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamtransaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TeamTransactionUpdateOne is the builder for updating a single TeamTransaction entity.
type TeamTransactionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeamTransactionMutation
}

// SetTeamID sets the "team_id" field.
func (_u *TeamTransactionUpdateOne) SetTeamID(v int64) *TeamTransactionUpdateOne {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *TeamTransactionUpdateOne) SetNillableTeamID(v *int64) *TeamTransactionUpdateOne {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetOperatorID sets the "operator_id" field.
func (_u *TeamTransactionUpdateOne) SetOperatorID(v int64) *TeamTransactionUpdateOne {
	_u.mutation.ResetOperatorID()
	_u.mutation.SetOperatorID(v)
	return _u
}

// SetNillableOperatorID sets the "operator_id" field if the given value is not nil.
func (_u *TeamTransactionUpdateOne) SetNillableOperatorID(v *int64) *TeamTransactionUpdateOne {
	if v != nil {
		_u.SetOperatorID(*v)
	}
	return _u
}

// AddOperatorID adds value to the "operator_id" field.
func (_u *TeamTransactionUpdateOne) AddOperatorID(v int64) *TeamTransactionUpdateOne {
	_u.mutation.AddOperatorID(v)
	return _u
}

// SetMemberID sets the "member_id" field.
func (_u *TeamTransactionUpdateOne) SetMemberID(v int64) *TeamTransactionUpdateOne {
	_u.mutation.ResetMemberID()
	_u.mutation.SetMemberID(v)
	return _u
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (_u *TeamTransactionUpdateOne) SetNillableMemberID(v *int64) *TeamTransactionUpdateOne {
	if v != nil {
		_u.SetMemberID(*v)
	}
	return _u
}

// AddMemberID adds value to the "member_id" field.
func (_u *TeamTransactionUpdateOne) AddMemberID(v int64) *TeamTransactionUpdateOne {
	_u.mutation.AddMemberID(v)
	return _u
}

// ClearMemberID clears the value of the "member_id" field.
func (_u *TeamTransactionUpdateOne) ClearMemberID() *TeamTransactionUpdateOne {
	_u.mutation.ClearMemberID()
	return _u
}

// SetAction sets the "action" field.
func (_u *TeamTransactionUpdateOne) SetAction(v string) *TeamTransactionUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *TeamTransactionUpdateOne) SetNillableAction(v *string) *TeamTransactionUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *TeamTransactionUpdateOne) SetAmount(v float64) *TeamTransactionUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *TeamTransactionUpdateOne) SetNillableAmount(v *float64) *TeamTransactionUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *TeamTransactionUpdateOne) AddAmount(v float64) *TeamTransactionUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetOwnerBalanceBefore sets the "owner_balance_before" field.
func (_u *TeamTransactionUpdateOne) SetOwnerBalanceBefore(v float64) *TeamTransactionUpdateOne {
	_u.mutation.ResetOwnerBalanceBefore()
	_u.mutation.SetOwnerBalanceBefore(v)
	return _u
}

// SetNillableOwnerBalanceBefore sets the "owner_balance_before" field if the given value is not nil.
func (_u *TeamTransactionUpdateOne) SetNillableOwnerBalanceBefore(v *float64) *TeamTransactionUpdateOne {
	if v != nil {
		_u.SetOwnerBalanceBefore(*v)
	}
	return _u
}

// AddOwnerBalanceBefore adds value to the "owner_balance_before" field.
func (_u *TeamTransactionUpdateOne) AddOwnerBalanceBefore(v float64) *TeamTransactionUpdateOne {
	_u.mutation.AddOwnerBalanceBefore(v)
	return _u
}

// SetOwnerBalanceAfter sets the "owner_balance_after" field.
func (_u *TeamTransactionUpdateOne) SetOwnerBalanceAfter(v float64) *TeamTransactionUpdateOne {
	_u.mutation.ResetOwnerBalanceAfter()
	_u.mutation.SetOwnerBalanceAfter(v)
	return _u
}

// SetNillableOwnerBalanceAfter sets the "owner_balance_after" field if the given value is not nil.
func (_u *TeamTransactionUpdateOne) SetNillableOwnerBalanceAfter(v *float64) *TeamTransactionUpdateOne {
	if v != nil {
		_u.SetOwnerBalanceAfter(*v)
	}
	return _u
}

// AddOwnerBalanceAfter adds value to the "owner_balance_after" field.
func (_u *TeamTransactionUpdateOne) AddOwnerBalanceAfter(v float64) *TeamTransactionUpdateOne {
	_u.mutation.AddOwnerBalanceAfter(v)
	return _u
}

// SetMemberBalanceBefore sets the "member_balance_before" field.
func (_u *TeamTransactionUpdateOne) SetMemberBalanceBefore(v float64) *TeamTransactionUpdateOne {
	_u.mutation.ResetMemberBalanceBefore()
	_u.mutation.SetMemberBalanceBefore(v)
	return _u
}

// SetNillableMemberBalanceBefore sets the "member_balance_before" field if the given value is not nil.
func (_u *TeamTransactionUpdateOne) SetNillableMemberBalanceBefore(v *float64) *TeamTransactionUpdateOne {
	if v != nil {
		_u.SetMemberBalanceBefore(*v)
	}
	return _u
}

// AddMemberBalanceBefore adds value to the "member_balance_before" field.
func (_u *TeamTransactionUpdateOne) AddMemberBalanceBefore(v float64) *TeamTransactionUpdateOne {
	_u.mutation.AddMemberBalanceBefore(v)
	return _u
}

// ClearMemberBalanceBefore clears the value of the "member_balance_before" field.
func (_u *TeamTransactionUpdateOne) ClearMemberBalanceBefore() *TeamTransactionUpdateOne {
	_u.mutation.ClearMemberBalanceBefore()
	return _u
}

// SetMemberBalanceAfter sets the "member_balance_after" field.
func (_u *TeamTransactionUpdateOne) SetMemberBalanceAfter(v float64) *TeamTransactionUpdateOne {
	_u.mutation.ResetMemberBalanceAfter()
	_u.mutation.SetMemberBalanceAfter(v)
	return _u
}

// SetNillableMemberBalanceAfter sets the "member_balance_after" field if the given value is not nil.
func (_u *TeamTransactionUpdateOne) SetNillableMemberBalanceAfter(v *float64) *TeamTransactionUpdateOne {
	if v != nil {
		_u.SetMemberBalanceAfter(*v)
	}
	return _u
}

// AddMemberBalanceAfter adds value to the "member_balance_after" field.
func (_u *TeamTransactionUpdateOne) AddMemberBalanceAfter(v float64) *TeamTransactionUpdateOne {
	_u.mutation.AddMemberBalanceAfter(v)
	return _u
}

// ClearMemberBalanceAfter clears the value of the "member_balance_after" field.
func (_u *TeamTransactionUpdateOne) ClearMemberBalanceAfter() *TeamTransactionUpdateOne {
	_u.mutation.ClearMemberBalanceAfter()
	return _u
}

// SetNote sets the "note" field.
func (_u *TeamTransactionUpdateOne) SetNote(v string) *TeamTransactionUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *TeamTransactionUpdateOne) SetNillableNote(v *string) *TeamTransactionUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *TeamTransactionUpdateOne) SetTeam(v *Team) *TeamTransactionUpdateOne {
	return _u.SetTeamID(v.ID)
}

// Mutation returns the TeamTransactionMutation object of the builder.
func (_u *TeamTransactionUpdateOne) Mutation() *TeamTransactionMutation {
	return _u.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *TeamTransactionUpdateOne) ClearTeam() *TeamTransactionUpdateOne {
	_u.mutation.ClearTeam()
	return _u
}

// Where appends a list predicates to the TeamTransactionUpdate builder.
func (_u *TeamTransactionUpdateOne) Where(ps ...predicate.TeamTransaction) *TeamTransactionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TeamTransactionUpdateOne) Select(field string, fields ...string) *TeamTransactionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TeamTransaction entity.
func (_u *TeamTransactionUpdateOne) Save(ctx context.Context) (*TeamTransaction, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamTransactionUpdateOne) SaveX(ctx context.Context) *TeamTransaction {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TeamTransactionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamTransactionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamTransactionUpdateOne) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := teamtransaction.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "TeamTransaction.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Note(); ok {
		if err := teamtransaction.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "TeamTransaction.note": %w`, err)}
		}
	}
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamTransaction.team"`)
	}
	return nil
}

func (_u *TeamTransactionUpdateOne) sqlSave(ctx context.Context) (_node *TeamTransaction, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamtransaction.Table, teamtransaction.Columns, sqlgraph.NewFieldSpec(teamtransaction.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TeamTransaction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teamtransaction.FieldID)
		for _, f := range fields {
			if !teamtransaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != teamtransaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OperatorID(); ok {
		_spec.SetField(teamtransaction.FieldOperatorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperatorID(); ok {
		_spec.AddField(teamtransaction.FieldOperatorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MemberID(); ok {
		_spec.SetField(teamtransaction.FieldMemberID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMemberID(); ok {
		_spec.AddField(teamtransaction.FieldMemberID, field.TypeInt64, value)
	}
	if _u.mutation.MemberIDCleared() {
		_spec.ClearField(teamtransaction.FieldMemberID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(teamtransaction.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(teamtransaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(teamtransaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OwnerBalanceBefore(); ok {
		_spec.SetField(teamtransaction.FieldOwnerBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOwnerBalanceBefore(); ok {
		_spec.AddField(teamtransaction.FieldOwnerBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OwnerBalanceAfter(); ok {
		_spec.SetField(teamtransaction.FieldOwnerBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOwnerBalanceAfter(); ok {
		_spec.AddField(teamtransaction.FieldOwnerBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MemberBalanceBefore(); ok {
		_spec.SetField(teamtransaction.FieldMemberBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMemberBalanceBefore(); ok {
		_spec.AddField(teamtransaction.FieldMemberBalanceBefore, field.TypeFloat64, value)
	}
	if _u.mutation.MemberBalanceBeforeCleared() {
		_spec.ClearField(teamtransaction.FieldMemberBalanceBefore, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MemberBalanceAfter(); ok {
		_spec.SetField(teamtransaction.FieldMemberBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMemberBalanceAfter(); ok {
		_spec.AddField(teamtransaction.FieldMemberBalanceAfter, field.TypeFloat64, value)
	}
	if _u.mutation.MemberBalanceAfterCleared() {
		_spec.ClearField(teamtransaction.FieldMemberBalanceAfter, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(teamtransaction.FieldNote, field.TypeString, value)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamtransaction.TeamTable,
			Columns: []string{teamtransaction.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teamtransaction.TeamTable,
			Columns: []string{teamtransaction.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TeamTransaction{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamtransaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
