// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/team"
	"github.com/Wei-Shaw/sub2api/ent/teamtransaction"
)

// TeamTransaction is the model entity for the TeamTransaction schema.
type TeamTransaction struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// TeamID holds the value of the "team_id" field.
	TeamID int64 `json:"team_id,omitempty"`
	// OperatorID holds the value of the "operator_id" field.
	OperatorID int64 `json:"operator_id,omitempty"`
	// MemberID holds the value of the "member_id" field.
	MemberID *int64 `json:"member_id,omitempty"`
	// Action holds the value of the "action" field.
	Action string `json:"action,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// OwnerBalanceBefore holds the value of the "owner_balance_before" field.
	OwnerBalanceBefore float64 `json:"owner_balance_before,omitempty"`
	// OwnerBalanceAfter holds the value of the "owner_balance_after" field.
	OwnerBalanceAfter float64 `json:"owner_balance_after,omitempty"`
	// MemberBalanceBefore holds the value of the "member_balance_before" field.
	MemberBalanceBefore *float64 `json:"member_balance_before,omitempty"`
	// MemberBalanceAfter holds the value of the "member_balance_after" field.
	MemberBalanceAfter *float64 `json:"member_balance_after,omitempty"`
	// Note holds the value of the "note" field.
	Note string `json:"note,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TeamTransactionQuery when eager-loading is set.
	Edges        TeamTransactionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TeamTransactionEdges holds the relations/edges for other nodes in the graph.
type TeamTransactionEdges struct {
	// Team holds the value of the team edge.
	Team *Team `json:"team,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TeamOrErr returns the Team value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TeamTransactionEdges) TeamOrErr() (*Team, error) {
	if e.Team != nil {
		return e.Team, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: team.Label}
	}
	return nil, &NotLoadedError{edge: "team"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TeamTransaction) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case teamtransaction.FieldAmount, teamtransaction.FieldOwnerBalanceBefore, teamtransaction.FieldOwnerBalanceAfter, teamtransaction.FieldMemberBalanceBefore, teamtransaction.FieldMemberBalanceAfter:
			values[i] = new(sql.NullFloat64)
		case teamtransaction.FieldID, teamtransaction.FieldTeamID, teamtransaction.FieldOperatorID, teamtransaction.FieldMemberID:
			values[i] = new(sql.NullInt64)
		case teamtransaction.FieldAction, teamtransaction.FieldNote:
			values[i] = new(sql.NullString)
		case teamtransaction.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TeamTransaction fields.
func (_m *TeamTransaction) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case teamtransaction.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case teamtransaction.FieldTeamID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field team_id", values[i])
			} else if value.Valid {
				_m.TeamID = value.Int64
			}
		case teamtransaction.FieldOperatorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field operator_id", values[i])
			} else if value.Valid {
				_m.OperatorID = value.Int64
			}
		case teamtransaction.FieldMemberID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field member_id", values[i])
			} else if value.Valid {
				_m.MemberID = new(int64)
				*_m.MemberID = value.Int64
			}
		case teamtransaction.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = value.String
			}
		case teamtransaction.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case teamtransaction.FieldOwnerBalanceBefore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_balance_before", values[i])
			} else if value.Valid {
				_m.OwnerBalanceBefore = value.Float64
			}
		case teamtransaction.FieldOwnerBalanceAfter:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_balance_after", values[i])
			} else if value.Valid {
				_m.OwnerBalanceAfter = value.Float64
			}
		case teamtransaction.FieldMemberBalanceBefore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field member_balance_before", values[i])
			} else if value.Valid {
				_m.MemberBalanceBefore = new(float64)
				*_m.MemberBalanceBefore = value.Float64
			}
		case teamtransaction.FieldMemberBalanceAfter:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field member_balance_after", values[i])
			} else if value.Valid {
				_m.MemberBalanceAfter = new(float64)
				*_m.MemberBalanceAfter = value.Float64
			}
		case teamtransaction.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = value.String
			}
		case teamtransaction.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TeamTransaction.
// This includes values selected through modifiers, order, etc.
func (_m *TeamTransaction) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTeam queries the "team" edge of the TeamTransaction entity.
func (_m *TeamTransaction) QueryTeam() *TeamQuery {
	return NewTeamTransactionClient(_m.config).QueryTeam(_m)
}

// Update returns a builder for updating this TeamTransaction.
// Note that you need to call TeamTransaction.Unwrap() before calling this method if this TeamTransaction
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TeamTransaction) Update() *TeamTransactionUpdateOne {
	return NewTeamTransactionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TeamTransaction entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TeamTransaction) Unwrap() *TeamTransaction {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TeamTransaction is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TeamTransaction) String() string {
	var builder strings.Builder
	builder.WriteString("TeamTransaction(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("team_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TeamID))
	builder.WriteString(", ")
	builder.WriteString("operator_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OperatorID))
	builder.WriteString(", ")
	if v := _m.MemberID; v != nil {
		builder.WriteString("member_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(_m.Action)
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("owner_balance_before=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerBalanceBefore))
	builder.WriteString(", ")
	builder.WriteString("owner_balance_after=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerBalanceAfter))
	builder.WriteString(", ")
	if v := _m.MemberBalanceBefore; v != nil {
		builder.WriteString("member_balance_before=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MemberBalanceAfter; v != nil {
		builder.WriteString("member_balance_after=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("note=")
	builder.WriteString(_m.Note)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TeamTransactions is a parsable slice of TeamTransaction.
type TeamTransactions []*TeamTransaction
