// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/team"
	"github.com/Wei-Shaw/sub2api/ent/teammembership"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// TeamMembershipCreate is the builder for creating a TeamMembership entity.
type TeamMembershipCreate struct {
	config
	mutation *TeamMembershipMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *TeamMembershipCreate) SetCreatedAt(v time.Time) *TeamMembershipCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TeamMembershipCreate) SetNillableCreatedAt(v *time.Time) *TeamMembershipCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TeamMembershipCreate) SetUpdatedAt(v time.Time) *TeamMembershipCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TeamMembershipCreate) SetNillableUpdatedAt(v *time.Time) *TeamMembershipCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTeamID sets the "team_id" field.
func (_c *TeamMembershipCreate) SetTeamID(v int64) *TeamMembershipCreate {
	_c.mutation.SetTeamID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *TeamMembershipCreate) SetUserID(v int64) *TeamMembershipCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetInvitedBy sets the "invited_by" field.
func (_c *TeamMembershipCreate) SetInvitedBy(v int64) *TeamMembershipCreate {
	_c.mutation.SetInvitedBy(v)
	return _c
}

// SetRemark sets the "remark" field.
func (_c *TeamMembershipCreate) SetRemark(v string) *TeamMembershipCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *TeamMembershipCreate) SetNillableRemark(v *string) *TeamMembershipCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *TeamMembershipCreate) SetStatus(v string) *TeamMembershipCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TeamMembershipCreate) SetNillableStatus(v *string) *TeamMembershipCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetJoinedAt sets the "joined_at" field.
func (_c *TeamMembershipCreate) SetJoinedAt(v time.Time) *TeamMembershipCreate {
	_c.mutation.SetJoinedAt(v)
	return _c
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_c *TeamMembershipCreate) SetNillableJoinedAt(v *time.Time) *TeamMembershipCreate {
	if v != nil {
		_c.SetJoinedAt(*v)
	}
	return _c
}

// SetExitRequestedAt sets the "exit_requested_at" field.
func (_c *TeamMembershipCreate) SetExitRequestedAt(v time.Time) *TeamMembershipCreate {
	_c.mutation.SetExitRequestedAt(v)
	return _c
}

// SetNillableExitRequestedAt sets the "exit_requested_at" field if the given value is not nil.
func (_c *TeamMembershipCreate) SetNillableExitRequestedAt(v *time.Time) *TeamMembershipCreate {
	if v != nil {
		_c.SetExitRequestedAt(*v)
	}
	return _c
}

// SetTeam sets the "team" edge to the Team entity.
func (_c *TeamMembershipCreate) SetTeam(v *Team) *TeamMembershipCreate {
	return _c.SetTeamID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *TeamMembershipCreate) SetUser(v *User) *TeamMembershipCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the TeamMembershipMutation object of the builder.
func (_c *TeamMembershipCreate) Mutation() *TeamMembershipMutation {
	return _c.mutation
}

// Save creates the TeamMembership in the database.
func (_c *TeamMembershipCreate) Save(ctx context.Context) (*TeamMembership, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TeamMembershipCreate) SaveX(ctx context.Context) *TeamMembership {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamMembershipCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamMembershipCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TeamMembershipCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := teammembership.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := teammembership.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Remark(); !ok {
		v := teammembership.DefaultRemark
		_c.mutation.SetRemark(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := teammembership.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TeamMembershipCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TeamMembership.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TeamMembership.updated_at"`)}
	}
	if _, ok := _c.mutation.TeamID(); !ok {
		return &ValidationError{Name: "team_id", err: errors.New(`ent: missing required field "TeamMembership.team_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "TeamMembership.user_id"`)}
	}
	if _, ok := _c.mutation.InvitedBy(); !ok {
		return &ValidationError{Name: "invited_by", err: errors.New(`ent: missing required field "TeamMembership.invited_by"`)}
	}
	if _, ok := _c.mutation.Remark(); !ok {
		return &ValidationError{Name: "remark", err: errors.New(`ent: missing required field "TeamMembership.remark"`)}
	}
	if v, ok := _c.mutation.Remark(); ok {
		if err := teammembership.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "TeamMembership.remark": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "TeamMembership.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := teammembership.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TeamMembership.status": %w`, err)}
		}
	}
	if len(_c.mutation.TeamIDs()) == 0 {
		return &ValidationError{Name: "team", err: errors.New(`ent: missing required edge "TeamMembership.team"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "TeamMembership.user"`)}
	}
	return nil
}

func (_c *TeamMembershipCreate) sqlSave(ctx context.Context) (*TeamMembership, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TeamMembershipCreate) createSpec() (*TeamMembership, *sqlgraph.CreateSpec) {
	var (
		_node = &TeamMembership{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(teammembership.Table, sqlgraph.NewFieldSpec(teammembership.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(teammembership.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(teammembership.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.InvitedBy(); ok {
		_spec.SetField(teammembership.FieldInvitedBy, field.TypeInt64, value)
		_node.InvitedBy = value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(teammembership.FieldRemark, field.TypeString, value)
		_node.Remark = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(teammembership.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.JoinedAt(); ok {
		_spec.SetField(teammembership.FieldJoinedAt, field.TypeTime, value)
		_node.JoinedAt = &value
	}
	if value, ok := _c.mutation.ExitRequestedAt(); ok {
		_spec.SetField(teammembership.FieldExitRequestedAt, field.TypeTime, value)
		_node.ExitRequestedAt = &value
	}
	if nodes := _c.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammembership.TeamTable,
			Columns: []string{teammembership.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TeamID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   teammembership.UserTable,
			Columns: []string{teammembership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamMembership.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamMembershipUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TeamMembershipCreate) OnConflict(opts ...sql.ConflictOption) *TeamMembershipUpsertOne {
	_c.conflict = opts
	return &TeamMembershipUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamMembership.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TeamMembershipCreate) OnConflictColumns(columns ...string) *TeamMembershipUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TeamMembershipUpsertOne{
		create: _c,
	}
}

type (
	// TeamMembershipUpsertOne is the builder for "upsert"-ing
	//  one TeamMembership node.
	TeamMembershipUpsertOne struct {
		create *TeamMembershipCreate
	}

	// TeamMembershipUpsert is the "OnConflict" setter.
	TeamMembershipUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamMembershipUpsert) SetUpdatedAt(v time.Time) *TeamMembershipUpsert {
	u.Set(teammembership.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamMembershipUpsert) UpdateUpdatedAt() *TeamMembershipUpsert {
	u.SetExcluded(teammembership.FieldUpdatedAt)
	return u
}

// SetTeamID sets the "team_id" field.
func (u *TeamMembershipUpsert) SetTeamID(v int64) *TeamMembershipUpsert {
	u.Set(teammembership.FieldTeamID, v)
	return u
}

// UpdateTeamID sets the "team_id" field to the value that was provided on create.
func (u *TeamMembershipUpsert) UpdateTeamID() *TeamMembershipUpsert {
	u.SetExcluded(teammembership.FieldTeamID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *TeamMembershipUpsert) SetUserID(v int64) *TeamMembershipUpsert {
	u.Set(teammembership.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TeamMembershipUpsert) UpdateUserID() *TeamMembershipUpsert {
	u.SetExcluded(teammembership.FieldUserID)
	return u
}

// SetInvitedBy sets the "invited_by" field.
func (u *TeamMembershipUpsert) SetInvitedBy(v int64) *TeamMembershipUpsert {
	u.Set(teammembership.FieldInvitedBy, v)
	return u
}

// UpdateInvitedBy sets the "invited_by" field to the value that was provided on create.
func (u *TeamMembershipUpsert) UpdateInvitedBy() *TeamMembershipUpsert {
	u.SetExcluded(teammembership.FieldInvitedBy)
	return u
}

// AddInvitedBy adds v to the "invited_by" field.
func (u *TeamMembershipUpsert) AddInvitedBy(v int64) *TeamMembershipUpsert {
	u.Add(teammembership.FieldInvitedBy, v)
	return u
}

// SetRemark sets the "remark" field.
func (u *TeamMembershipUpsert) SetRemark(v string) *TeamMembershipUpsert {
	u.Set(teammembership.FieldRemark, v)
	return u
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *TeamMembershipUpsert) UpdateRemark() *TeamMembershipUpsert {
	u.SetExcluded(teammembership.FieldRemark)
	return u
}

// SetStatus sets the "status" field.
func (u *TeamMembershipUpsert) SetStatus(v string) *TeamMembershipUpsert {
	u.Set(teammembership.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TeamMembershipUpsert) UpdateStatus() *TeamMembershipUpsert {
	u.SetExcluded(teammembership.FieldStatus)
	return u
}

// SetJoinedAt sets the "joined_at" field.
func (u *TeamMembershipUpsert) SetJoinedAt(v time.Time) *TeamMembershipUpsert {
	u.Set(teammembership.FieldJoinedAt, v)
	return u
}

// UpdateJoinedAt sets the "joined_at" field to the value that was provided on create.
func (u *TeamMembershipUpsert) UpdateJoinedAt() *TeamMembershipUpsert {
	u.SetExcluded(teammembership.FieldJoinedAt)
	return u
}

// ClearJoinedAt clears the value of the "joined_at" field.
func (u *TeamMembershipUpsert) ClearJoinedAt() *TeamMembershipUpsert {
	u.SetNull(teammembership.FieldJoinedAt)
	return u
}

// SetExitRequestedAt sets the "exit_requested_at" field.
func (u *TeamMembershipUpsert) SetExitRequestedAt(v time.Time) *TeamMembershipUpsert {
	u.Set(teammembership.FieldExitRequestedAt, v)
	return u
}

// UpdateExitRequestedAt sets the "exit_requested_at" field to the value that was provided on create.
func (u *TeamMembershipUpsert) UpdateExitRequestedAt() *TeamMembershipUpsert {
	u.SetExcluded(teammembership.FieldExitRequestedAt)
	return u
}

// ClearExitRequestedAt clears the value of the "exit_requested_at" field.
func (u *TeamMembershipUpsert) ClearExitRequestedAt() *TeamMembershipUpsert {
	u.SetNull(teammembership.FieldExitRequestedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TeamMembership.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamMembershipUpsertOne) UpdateNewValues() *TeamMembershipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(teammembership.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamMembership.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TeamMembershipUpsertOne) Ignore() *TeamMembershipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamMembershipUpsertOne) DoNothing() *TeamMembershipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamMembershipCreate.OnConflict
// documentation for more info.
func (u *TeamMembershipUpsertOne) Update(set func(*TeamMembershipUpsert)) *TeamMembershipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamMembershipUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamMembershipUpsertOne) SetUpdatedAt(v time.Time) *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamMembershipUpsertOne) UpdateUpdatedAt() *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTeamID sets the "team_id" field.
func (u *TeamMembershipUpsertOne) SetTeamID(v int64) *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetTeamID(v)
	})
}

// UpdateTeamID sets the "team_id" field to the value that was provided on create.
func (u *TeamMembershipUpsertOne) UpdateTeamID() *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateTeamID()
	})
}

// SetUserID sets the "user_id" field.
func (u *TeamMembershipUpsertOne) SetUserID(v int64) *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TeamMembershipUpsertOne) UpdateUserID() *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateUserID()
	})
}

// SetInvitedBy sets the "invited_by" field.
func (u *TeamMembershipUpsertOne) SetInvitedBy(v int64) *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetInvitedBy(v)
	})
}

// AddInvitedBy adds v to the "invited_by" field.
func (u *TeamMembershipUpsertOne) AddInvitedBy(v int64) *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.AddInvitedBy(v)
	})
}

// UpdateInvitedBy sets the "invited_by" field to the value that was provided on create.
func (u *TeamMembershipUpsertOne) UpdateInvitedBy() *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateInvitedBy()
	})
}

// SetRemark sets the "remark" field.
func (u *TeamMembershipUpsertOne) SetRemark(v string) *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *TeamMembershipUpsertOne) UpdateRemark() *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateRemark()
	})
}

// SetStatus sets the "status" field.
func (u *TeamMembershipUpsertOne) SetStatus(v string) *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TeamMembershipUpsertOne) UpdateStatus() *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateStatus()
	})
}

// SetJoinedAt sets the "joined_at" field.
func (u *TeamMembershipUpsertOne) SetJoinedAt(v time.Time) *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetJoinedAt(v)
	})
}

// UpdateJoinedAt sets the "joined_at" field to the value that was provided on create.
func (u *TeamMembershipUpsertOne) UpdateJoinedAt() *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateJoinedAt()
	})
}

// ClearJoinedAt clears the value of the "joined_at" field.
func (u *TeamMembershipUpsertOne) ClearJoinedAt() *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.ClearJoinedAt()
	})
}

// SetExitRequestedAt sets the "exit_requested_at" field.
func (u *TeamMembershipUpsertOne) SetExitRequestedAt(v time.Time) *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetExitRequestedAt(v)
	})
}

// UpdateExitRequestedAt sets the "exit_requested_at" field to the value that was provided on create.
func (u *TeamMembershipUpsertOne) UpdateExitRequestedAt() *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateExitRequestedAt()
	})
}

// ClearExitRequestedAt clears the value of the "exit_requested_at" field.
func (u *TeamMembershipUpsertOne) ClearExitRequestedAt() *TeamMembershipUpsertOne {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.ClearExitRequestedAt()
	})
}

// Exec executes the query.
func (u *TeamMembershipUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamMembershipCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamMembershipUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TeamMembershipUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TeamMembershipUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TeamMembershipCreateBulk is the builder for creating many TeamMembership entities in bulk.
type TeamMembershipCreateBulk struct {
	config
	err      error
	builders []*TeamMembershipCreate
	conflict []sql.ConflictOption
}

// Save creates the TeamMembership entities in the database.
func (_c *TeamMembershipCreateBulk) Save(ctx context.Context) ([]*TeamMembership, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TeamMembership, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TeamMembershipMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TeamMembershipCreateBulk) SaveX(ctx context.Context) []*TeamMembership {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamMembershipCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamMembershipCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamMembership.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamMembershipUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TeamMembershipCreateBulk) OnConflict(opts ...sql.ConflictOption) *TeamMembershipUpsertBulk {
	_c.conflict = opts
	return &TeamMembershipUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamMembership.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TeamMembershipCreateBulk) OnConflictColumns(columns ...string) *TeamMembershipUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TeamMembershipUpsertBulk{
		create: _c,
	}
}

// TeamMembershipUpsertBulk is the builder for "upsert"-ing
// a bulk of TeamMembership nodes.
type TeamMembershipUpsertBulk struct {
	create *TeamMembershipCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TeamMembership.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamMembershipUpsertBulk) UpdateNewValues() *TeamMembershipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(teammembership.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamMembership.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TeamMembershipUpsertBulk) Ignore() *TeamMembershipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamMembershipUpsertBulk) DoNothing() *TeamMembershipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamMembershipCreateBulk.OnConflict
// documentation for more info.
func (u *TeamMembershipUpsertBulk) Update(set func(*TeamMembershipUpsert)) *TeamMembershipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamMembershipUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TeamMembershipUpsertBulk) SetUpdatedAt(v time.Time) *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TeamMembershipUpsertBulk) UpdateUpdatedAt() *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTeamID sets the "team_id" field.
func (u *TeamMembershipUpsertBulk) SetTeamID(v int64) *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetTeamID(v)
	})
}

// UpdateTeamID sets the "team_id" field to the value that was provided on create.
func (u *TeamMembershipUpsertBulk) UpdateTeamID() *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateTeamID()
	})
}

// SetUserID sets the "user_id" field.
func (u *TeamMembershipUpsertBulk) SetUserID(v int64) *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TeamMembershipUpsertBulk) UpdateUserID() *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateUserID()
	})
}

// SetInvitedBy sets the "invited_by" field.
func (u *TeamMembershipUpsertBulk) SetInvitedBy(v int64) *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetInvitedBy(v)
	})
}

// AddInvitedBy adds v to the "invited_by" field.
func (u *TeamMembershipUpsertBulk) AddInvitedBy(v int64) *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.AddInvitedBy(v)
	})
}

// UpdateInvitedBy sets the "invited_by" field to the value that was provided on create.
func (u *TeamMembershipUpsertBulk) UpdateInvitedBy() *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateInvitedBy()
	})
}

// SetRemark sets the "remark" field.
func (u *TeamMembershipUpsertBulk) SetRemark(v string) *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *TeamMembershipUpsertBulk) UpdateRemark() *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateRemark()
	})
}

// SetStatus sets the "status" field.
func (u *TeamMembershipUpsertBulk) SetStatus(v string) *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TeamMembershipUpsertBulk) UpdateStatus() *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateStatus()
	})
}

// SetJoinedAt sets the "joined_at" field.
func (u *TeamMembershipUpsertBulk) SetJoinedAt(v time.Time) *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetJoinedAt(v)
	})
}

// UpdateJoinedAt sets the "joined_at" field to the value that was provided on create.
func (u *TeamMembershipUpsertBulk) UpdateJoinedAt() *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateJoinedAt()
	})
}

// ClearJoinedAt clears the value of the "joined_at" field.
func (u *TeamMembershipUpsertBulk) ClearJoinedAt() *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.ClearJoinedAt()
	})
}

// SetExitRequestedAt sets the "exit_requested_at" field.
func (u *TeamMembershipUpsertBulk) SetExitRequestedAt(v time.Time) *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.SetExitRequestedAt(v)
	})
}

// UpdateExitRequestedAt sets the "exit_requested_at" field to the value that was provided on create.
func (u *TeamMembershipUpsertBulk) UpdateExitRequestedAt() *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.UpdateExitRequestedAt()
	})
}

// ClearExitRequestedAt clears the value of the "exit_requested_at" field.
func (u *TeamMembershipUpsertBulk) ClearExitRequestedAt() *TeamMembershipUpsertBulk {
	return u.Update(func(s *TeamMembershipUpsert) {
		s.ClearExitRequestedAt()
	})
}

// Exec executes the query.
func (u *TeamMembershipUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TeamMembershipCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamMembershipCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamMembershipUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
