// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/team"
	"github.com/Wei-Shaw/sub2api/ent/teammembership"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// TeamMembershipUpdate is the builder for updating TeamMembership entities.
type TeamMembershipUpdate struct {
	config
	hooks    []Hook
	mutation *TeamMembershipMutation
}

// Where appends a list predicates to the TeamMembershipUpdate builder.
func (_u *TeamMembershipUpdate) Where(ps ...predicate.TeamMembership) *TeamMembershipUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TeamMembershipUpdate) SetUpdatedAt(v time.Time) *TeamMembershipUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *TeamMembershipUpdate) SetTeamID(v int64) *TeamMembershipUpdate {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *TeamMembershipUpdate) SetNillableTeamID(v *int64) *TeamMembershipUpdate {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TeamMembershipUpdate) SetUserID(v int64) *TeamMembershipUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TeamMembershipUpdate) SetNillableUserID(v *int64) *TeamMembershipUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetInvitedBy sets the "invited_by" field.
func (_u *TeamMembershipUpdate) SetInvitedBy(v int64) *TeamMembershipUpdate {
	_u.mutation.ResetInvitedBy()
	_u.mutation.SetInvitedBy(v)
	return _u
}

// SetNillableInvitedBy sets the "invited_by" field if the given value is not nil.
func (_u *TeamMembershipUpdate) SetNillableInvitedBy(v *int64) *TeamMembershipUpdate {
	if v != nil {
		_u.SetInvitedBy(*v)
	}
	return _u
}

// AddInvitedBy adds value to the "invited_by" field.
func (_u *TeamMembershipUpdate) AddInvitedBy(v int64) *TeamMembershipUpdate {
	_u.mutation.AddInvitedBy(v)
	return _u
}

// SetRemark sets the "remark" field.
func (_u *TeamMembershipUpdate) SetRemark(v string) *TeamMembershipUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *TeamMembershipUpdate) SetNillableRemark(v *string) *TeamMembershipUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TeamMembershipUpdate) SetStatus(v string) *TeamMembershipUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TeamMembershipUpdate) SetNillableStatus(v *string) *TeamMembershipUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetJoinedAt sets the "joined_at" field.
func (_u *TeamMembershipUpdate) SetJoinedAt(v time.Time) *TeamMembershipUpdate {
	_u.mutation.SetJoinedAt(v)
	return _u
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_u *TeamMembershipUpdate) SetNillableJoinedAt(v *time.Time) *TeamMembershipUpdate {
	if v != nil {
		_u.SetJoinedAt(*v)
	}
	return _u
}

// ClearJoinedAt clears the value of the "joined_at" field.
func (_u *TeamMembershipUpdate) ClearJoinedAt() *TeamMembershipUpdate {
	_u.mutation.ClearJoinedAt()
	return _u
}

// SetExitRequestedAt sets the "exit_requested_at" field.
func (_u *TeamMembershipUpdate) SetExitRequestedAt(v time.Time) *TeamMembershipUpdate {
	_u.mutation.SetExitRequestedAt(v)
	return _u
}

// SetNillableExitRequestedAt sets the "exit_requested_at" field if the given value is not nil.
func (_u *TeamMembershipUpdate) SetNillableExitRequestedAt(v *time.Time) *TeamMembershipUpdate {
	if v != nil {
		_u.SetExitRequestedAt(*v)
	}
	return _u
}

// ClearExitRequestedAt clears the value of the "exit_requested_at" field.
func (_u *TeamMembershipUpdate) ClearExitRequestedAt() *TeamMembershipUpdate {
	_u.mutation.ClearExitRequestedAt()
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *TeamMembershipUpdate) SetTeam(v *Team) *TeamMembershipUpdate {
	return _u.SetTeamID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *TeamMembershipUpdate) SetUser(v *User) *TeamMembershipUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the TeamMembershipMutation object of the builder.
func (_u *TeamMembershipUpdate) Mutation() *TeamMembershipMutation {
	return _u.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *TeamMembershipUpdate) ClearTeam() *TeamMembershipUpdate {
	_u.mutation.ClearTeam()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TeamMembershipUpdate) ClearUser() *TeamMembershipUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TeamMembershipUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamMembershipUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TeamMembershipUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamMembershipUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeamMembershipUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := teammembership.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamMembershipUpdate) check() error {
	if v, ok := _u.mutation.Remark(); ok {
		if err := teammembership.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "TeamMembership.remark": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := teammembership.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TeamMembership.status": %w`, err)}
		}
	}
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamMembership.team"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamMembership.user"`)
	}
	return nil
}

func (_u *TeamMembershipUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teammembership.Table, teammembership.Columns, sqlgraph.NewFieldSpec(teammembership.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(teammembership.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.InvitedBy(); ok {
		_spec.SetField(teammembership.FieldInvitedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInvitedBy(); ok {
		_spec.AddField(teammembership.FieldInvitedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(teammembership.FieldRemark, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(teammembership.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.JoinedAt(); ok {
		_spec.SetField(teammembership.FieldJoinedAt, field.TypeTime, value)
	}
	if _u.mutation.JoinedAtCleared() {
		_spec.ClearField(teammembership.FieldJoinedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExitRequestedAt(); ok {
		_spec.SetField(teammembership.FieldExitRequestedAt, field.TypeTime, value)
	}
	if _u.mutation.ExitRequestedAtCleared() {
		_spec.ClearField(teammembership.FieldExitRequestedAt, field.TypeTime)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammembership.TeamTable,
			Columns: []string{teammembership.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammembership.TeamTable,
			Columns: []string{teammembership.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   teammembership.UserTable,
			Columns: []string{teammembership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   teammembership.UserTable,
			Columns: []string{teammembership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teammembership.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TeamMembershipUpdateOne is the builder for updating a single TeamMembership entity.
type TeamMembershipUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeamMembershipMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TeamMembershipUpdateOne) SetUpdatedAt(v time.Time) *TeamMembershipUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *TeamMembershipUpdateOne) SetTeamID(v int64) *TeamMembershipUpdateOne {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *TeamMembershipUpdateOne) SetNillableTeamID(v *int64) *TeamMembershipUpdateOne {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TeamMembershipUpdateOne) SetUserID(v int64) *TeamMembershipUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TeamMembershipUpdateOne) SetNillableUserID(v *int64) *TeamMembershipUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetInvitedBy sets the "invited_by" field.
func (_u *TeamMembershipUpdateOne) SetInvitedBy(v int64) *TeamMembershipUpdateOne {
	_u.mutation.ResetInvitedBy()
	_u.mutation.SetInvitedBy(v)
	return _u
}

// SetNillableInvitedBy sets the "invited_by" field if the given value is not nil.
func (_u *TeamMembershipUpdateOne) SetNillableInvitedBy(v *int64) *TeamMembershipUpdateOne {
	if v != nil {
		_u.SetInvitedBy(*v)
	}
	return _u
}

// AddInvitedBy adds value to the "invited_by" field.
func (_u *TeamMembershipUpdateOne) AddInvitedBy(v int64) *TeamMembershipUpdateOne {
	_u.mutation.AddInvitedBy(v)
	return _u
}

// SetRemark sets the "remark" field.
func (_u *TeamMembershipUpdateOne) SetRemark(v string) *TeamMembershipUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *TeamMembershipUpdateOne) SetNillableRemark(v *string) *TeamMembershipUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TeamMembershipUpdateOne) SetStatus(v string) *TeamMembershipUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TeamMembershipUpdateOne) SetNillableStatus(v *string) *TeamMembershipUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetJoinedAt sets the "joined_at" field.
func (_u *TeamMembershipUpdateOne) SetJoinedAt(v time.Time) *TeamMembershipUpdateOne {
	_u.mutation.SetJoinedAt(v)
	return _u
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_u *TeamMembershipUpdateOne) SetNillableJoinedAt(v *time.Time) *TeamMembershipUpdateOne {
	if v != nil {
		_u.SetJoinedAt(*v)
	}
	return _u
}

// ClearJoinedAt clears the value of the "joined_at" field.
func (_u *TeamMembershipUpdateOne) ClearJoinedAt() *TeamMembershipUpdateOne {
	_u.mutation.ClearJoinedAt()
	return _u
}

// SetExitRequestedAt sets the "exit_requested_at" field.
func (_u *TeamMembershipUpdateOne) SetExitRequestedAt(v time.Time) *TeamMembershipUpdateOne {
	_u.mutation.SetExitRequestedAt(v)
	return _u
}

// SetNillableExitRequestedAt sets the "exit_requested_at" field if the given value is not nil.
func (_u *TeamMembershipUpdateOne) SetNillableExitRequestedAt(v *time.Time) *TeamMembershipUpdateOne {
	if v != nil {
		_u.SetExitRequestedAt(*v)
	}
	return _u
}

// ClearExitRequestedAt clears the value of the "exit_requested_at" field.
func (_u *TeamMembershipUpdateOne) ClearExitRequestedAt() *TeamMembershipUpdateOne {
	_u.mutation.ClearExitRequestedAt()
	return _u
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *TeamMembershipUpdateOne) SetTeam(v *Team) *TeamMembershipUpdateOne {
	return _u.SetTeamID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *TeamMembershipUpdateOne) SetUser(v *User) *TeamMembershipUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the TeamMembershipMutation object of the builder.
func (_u *TeamMembershipUpdateOne) Mutation() *TeamMembershipMutation {
	return _u.mutation
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *TeamMembershipUpdateOne) ClearTeam() *TeamMembershipUpdateOne {
	_u.mutation.ClearTeam()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TeamMembershipUpdateOne) ClearUser() *TeamMembershipUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the TeamMembershipUpdate builder.
func (_u *TeamMembershipUpdateOne) Where(ps ...predicate.TeamMembership) *TeamMembershipUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TeamMembershipUpdateOne) Select(field string, fields ...string) *TeamMembershipUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TeamMembership entity.
func (_u *TeamMembershipUpdateOne) Save(ctx context.Context) (*TeamMembership, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamMembershipUpdateOne) SaveX(ctx context.Context) *TeamMembership {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TeamMembershipUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamMembershipUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeamMembershipUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := teammembership.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamMembershipUpdateOne) check() error {
	if v, ok := _u.mutation.Remark(); ok {
		if err := teammembership.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "TeamMembership.remark": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := teammembership.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TeamMembership.status": %w`, err)}
		}
	}
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamMembership.team"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamMembership.user"`)
	}
	return nil
}

func (_u *TeamMembershipUpdateOne) sqlSave(ctx context.Context) (_node *TeamMembership, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teammembership.Table, teammembership.Columns, sqlgraph.NewFieldSpec(teammembership.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TeamMembership.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teammembership.FieldID)
		for _, f := range fields {
			if !teammembership.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != teammembership.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(teammembership.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.InvitedBy(); ok {
		_spec.SetField(teammembership.FieldInvitedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInvitedBy(); ok {
		_spec.AddField(teammembership.FieldInvitedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(teammembership.FieldRemark, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(teammembership.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.JoinedAt(); ok {
		_spec.SetField(teammembership.FieldJoinedAt, field.TypeTime, value)
	}
	if _u.mutation.JoinedAtCleared() {
		_spec.ClearField(teammembership.FieldJoinedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExitRequestedAt(); ok {
		_spec.SetField(teammembership.FieldExitRequestedAt, field.TypeTime, value)
	}
	if _u.mutation.ExitRequestedAtCleared() {
		_spec.ClearField(teammembership.FieldExitRequestedAt, field.TypeTime)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammembership.TeamTable,
			Columns: []string{teammembership.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammembership.TeamTable,
			Columns: []string{teammembership.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   teammembership.UserTable,
			Columns: []string{teammembership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   teammembership.UserTable,
			Columns: []string{teammembership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TeamMembership{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teammembership.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
