// Code generated by ent, DO NOT EDIT.

package teammembership

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldUpdatedAt, v))
}

// TeamID applies equality check predicate on the "team_id" field. It's identical to TeamIDEQ.
func TeamID(v int64) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldTeamID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldUserID, v))
}

// InvitedBy applies equality check predicate on the "invited_by" field. It's identical to InvitedByEQ.
func InvitedBy(v int64) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldInvitedBy, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldRemark, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldStatus, v))
}

// JoinedAt applies equality check predicate on the "joined_at" field. It's identical to JoinedAtEQ.
func JoinedAt(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldJoinedAt, v))
}

// ExitRequestedAt applies equality check predicate on the "exit_requested_at" field. It's identical to ExitRequestedAtEQ.
func ExitRequestedAt(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldExitRequestedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldLTE(FieldUpdatedAt, v))
}

// TeamIDEQ applies the EQ predicate on the "team_id" field.
func TeamIDEQ(v int64) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldTeamID, v))
}

// TeamIDNEQ applies the NEQ predicate on the "team_id" field.
func TeamIDNEQ(v int64) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNEQ(FieldTeamID, v))
}

// TeamIDIn applies the In predicate on the "team_id" field.
func TeamIDIn(vs ...int64) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldIn(FieldTeamID, vs...))
}

// TeamIDNotIn applies the NotIn predicate on the "team_id" field.
func TeamIDNotIn(vs ...int64) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNotIn(FieldTeamID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNotIn(FieldUserID, vs...))
}

// InvitedByEQ applies the EQ predicate on the "invited_by" field.
func InvitedByEQ(v int64) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldInvitedBy, v))
}

// InvitedByNEQ applies the NEQ predicate on the "invited_by" field.
func InvitedByNEQ(v int64) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNEQ(FieldInvitedBy, v))
}

// InvitedByIn applies the In predicate on the "invited_by" field.
func InvitedByIn(vs ...int64) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldIn(FieldInvitedBy, vs...))
}

// InvitedByNotIn applies the NotIn predicate on the "invited_by" field.
func InvitedByNotIn(vs ...int64) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNotIn(FieldInvitedBy, vs...))
}

// InvitedByGT applies the GT predicate on the "invited_by" field.
func InvitedByGT(v int64) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldGT(FieldInvitedBy, v))
}

// InvitedByGTE applies the GTE predicate on the "invited_by" field.
func InvitedByGTE(v int64) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldGTE(FieldInvitedBy, v))
}

// InvitedByLT applies the LT predicate on the "invited_by" field.
func InvitedByLT(v int64) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldLT(FieldInvitedBy, v))
}

// InvitedByLTE applies the LTE predicate on the "invited_by" field.
func InvitedByLTE(v int64) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldLTE(FieldInvitedBy, v))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldContainsFold(FieldRemark, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldContainsFold(FieldStatus, v))
}

// JoinedAtEQ applies the EQ predicate on the "joined_at" field.
func JoinedAtEQ(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldJoinedAt, v))
}

// JoinedAtNEQ applies the NEQ predicate on the "joined_at" field.
func JoinedAtNEQ(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNEQ(FieldJoinedAt, v))
}

// JoinedAtIn applies the In predicate on the "joined_at" field.
func JoinedAtIn(vs ...time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldIn(FieldJoinedAt, vs...))
}

// JoinedAtNotIn applies the NotIn predicate on the "joined_at" field.
func JoinedAtNotIn(vs ...time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNotIn(FieldJoinedAt, vs...))
}

// JoinedAtGT applies the GT predicate on the "joined_at" field.
func JoinedAtGT(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldGT(FieldJoinedAt, v))
}

// JoinedAtGTE applies the GTE predicate on the "joined_at" field.
func JoinedAtGTE(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldGTE(FieldJoinedAt, v))
}

// JoinedAtLT applies the LT predicate on the "joined_at" field.
func JoinedAtLT(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldLT(FieldJoinedAt, v))
}

// JoinedAtLTE applies the LTE predicate on the "joined_at" field.
func JoinedAtLTE(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldLTE(FieldJoinedAt, v))
}

// JoinedAtIsNil applies the IsNil predicate on the "joined_at" field.
func JoinedAtIsNil() predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldIsNull(FieldJoinedAt))
}

// JoinedAtNotNil applies the NotNil predicate on the "joined_at" field.
func JoinedAtNotNil() predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNotNull(FieldJoinedAt))
}

// ExitRequestedAtEQ applies the EQ predicate on the "exit_requested_at" field.
func ExitRequestedAtEQ(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldExitRequestedAt, v))
}

// ExitRequestedAtNEQ applies the NEQ predicate on the "exit_requested_at" field.
func ExitRequestedAtNEQ(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNEQ(FieldExitRequestedAt, v))
}

// ExitRequestedAtIn applies the In predicate on the "exit_requested_at" field.
func ExitRequestedAtIn(vs ...time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldIn(FieldExitRequestedAt, vs...))
}

// ExitRequestedAtNotIn applies the NotIn predicate on the "exit_requested_at" field.
func ExitRequestedAtNotIn(vs ...time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNotIn(FieldExitRequestedAt, vs...))
}

// ExitRequestedAtGT applies the GT predicate on the "exit_requested_at" field.
func ExitRequestedAtGT(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldGT(FieldExitRequestedAt, v))
}

// ExitRequestedAtGTE applies the GTE predicate on the "exit_requested_at" field.
func ExitRequestedAtGTE(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldGTE(FieldExitRequestedAt, v))
}

// ExitRequestedAtLT applies the LT predicate on the "exit_requested_at" field.
func ExitRequestedAtLT(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldLT(FieldExitRequestedAt, v))
}

// ExitRequestedAtLTE applies the LTE predicate on the "exit_requested_at" field.
func ExitRequestedAtLTE(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldLTE(FieldExitRequestedAt, v))
}

// ExitRequestedAtIsNil applies the IsNil predicate on the "exit_requested_at" field.
func ExitRequestedAtIsNil() predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldIsNull(FieldExitRequestedAt))
}

// ExitRequestedAtNotNil applies the NotNil predicate on the "exit_requested_at" field.
func ExitRequestedAtNotNil() predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNotNull(FieldExitRequestedAt))
}

// HasTeam applies the HasEdge predicate on the "team" edge.
func HasTeam() predicate.TeamMembership {
	return predicate.TeamMembership(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TeamTable, TeamColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamWith applies the HasEdge predicate on the "team" edge with a given conditions (other predicates).
func HasTeamWith(preds ...predicate.Team) predicate.TeamMembership {
	return predicate.TeamMembership(func(s *sql.Selector) {
		step := newTeamStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.TeamMembership {
	return predicate.TeamMembership(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.TeamMembership {
	return predicate.TeamMembership(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TeamMembership) predicate.TeamMembership {
	return predicate.TeamMembership(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TeamMembership) predicate.TeamMembership {
	return predicate.TeamMembership(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TeamMembership) predicate.TeamMembership {
	return predicate.TeamMembership(sql.NotPredicates(p))
}
