// Code generated by ent, DO NOT EDIT.

package teamtransaction

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the teamtransaction type in the database.
	Label = "team_transaction"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTeamID holds the string denoting the team_id field in the database.
	FieldTeamID = "team_id"
	// FieldOperatorID holds the string denoting the operator_id field in the database.
	FieldOperatorID = "operator_id"
	// FieldMemberID holds the string denoting the member_id field in the database.
	FieldMemberID = "member_id"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldOwnerBalanceBefore holds the string denoting the owner_balance_before field in the database.
	FieldOwnerBalanceBefore = "owner_balance_before"
	// FieldOwnerBalanceAfter holds the string denoting the owner_balance_after field in the database.
	FieldOwnerBalanceAfter = "owner_balance_after"
	// FieldMemberBalanceBefore holds the string denoting the member_balance_before field in the database.
	FieldMemberBalanceBefore = "member_balance_before"
	// FieldMemberBalanceAfter holds the string denoting the member_balance_after field in the database.
	FieldMemberBalanceAfter = "member_balance_after"
	// FieldNote holds the string denoting the note field in the database.
	FieldNote = "note"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeTeam holds the string denoting the team edge name in mutations.
	EdgeTeam = "team"
	// Table holds the table name of the teamtransaction in the database.
	Table = "team_transactions"
	// TeamTable is the table that holds the team relation/edge.
	TeamTable = "team_transactions"
	// TeamInverseTable is the table name for the Team entity.
	// It exists in this package in order to avoid circular dependency with the "team" package.
	TeamInverseTable = "teams"
	// TeamColumn is the table column denoting the team relation/edge.
	TeamColumn = "team_id"
)

// Columns holds all SQL columns for teamtransaction fields.
var Columns = []string{
	FieldID,
	FieldTeamID,
	FieldOperatorID,
	FieldMemberID,
	FieldAction,
	FieldAmount,
	FieldOwnerBalanceBefore,
	FieldOwnerBalanceAfter,
	FieldMemberBalanceBefore,
	FieldMemberBalanceAfter,
	FieldNote,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ActionValidator is a validator for the "action" field. It is called by the builders before save.
	ActionValidator func(string) error
	// DefaultAmount holds the default value on creation for the "amount" field.
	DefaultAmount float64
	// DefaultOwnerBalanceBefore holds the default value on creation for the "owner_balance_before" field.
	DefaultOwnerBalanceBefore float64
	// DefaultOwnerBalanceAfter holds the default value on creation for the "owner_balance_after" field.
	DefaultOwnerBalanceAfter float64
	// DefaultNote holds the default value on creation for the "note" field.
	DefaultNote string
	// NoteValidator is a validator for the "note" field. It is called by the builders before save.
	NoteValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the TeamTransaction queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTeamID orders the results by the team_id field.
func ByTeamID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTeamID, opts...).ToFunc()
}

// ByOperatorID orders the results by the operator_id field.
func ByOperatorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperatorID, opts...).ToFunc()
}

// ByMemberID orders the results by the member_id field.
func ByMemberID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMemberID, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByOwnerBalanceBefore orders the results by the owner_balance_before field.
func ByOwnerBalanceBefore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerBalanceBefore, opts...).ToFunc()
}

// ByOwnerBalanceAfter orders the results by the owner_balance_after field.
func ByOwnerBalanceAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerBalanceAfter, opts...).ToFunc()
}

// ByMemberBalanceBefore orders the results by the member_balance_before field.
func ByMemberBalanceBefore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMemberBalanceBefore, opts...).ToFunc()
}

// ByMemberBalanceAfter orders the results by the member_balance_after field.
func ByMemberBalanceAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMemberBalanceAfter, opts...).ToFunc()
}

// ByNote orders the results by the note field.
func ByNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNote, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByTeamField orders the results by team field.
func ByTeamField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTeamStep(), sql.OrderByField(field, opts...))
	}
}
func newTeamStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TeamInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TeamTable, TeamColumn),
	)
}
