// Code generated by ent, DO NOT EDIT.

package teamtransaction

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldLTE(FieldID, id))
}

// TeamID applies equality check predicate on the "team_id" field. It's identical to TeamIDEQ.
func TeamID(v int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldEQ(FieldTeamID, v))
}

// OperatorID applies equality check predicate on the "operator_id" field. It's identical to OperatorIDEQ.
func OperatorID(v int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldEQ(FieldOperatorID, v))
}

// MemberID applies equality check predicate on the "member_id" field. It's identical to MemberIDEQ.
func MemberID(v int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldEQ(FieldMemberID, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldEQ(FieldAction, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldEQ(FieldAmount, v))
}

// OwnerBalanceBefore applies equality check predicate on the "owner_balance_before" field. It's identical to OwnerBalanceBeforeEQ.
func OwnerBalanceBefore(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldEQ(FieldOwnerBalanceBefore, v))
}

// OwnerBalanceAfter applies equality check predicate on the "owner_balance_after" field. It's identical to OwnerBalanceAfterEQ.
func OwnerBalanceAfter(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldEQ(FieldOwnerBalanceAfter, v))
}

// MemberBalanceBefore applies equality check predicate on the "member_balance_before" field. It's identical to MemberBalanceBeforeEQ.
func MemberBalanceBefore(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldEQ(FieldMemberBalanceBefore, v))
}

// MemberBalanceAfter applies equality check predicate on the "member_balance_after" field. It's identical to MemberBalanceAfterEQ.
func MemberBalanceAfter(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldEQ(FieldMemberBalanceAfter, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldEQ(FieldNote, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldEQ(FieldCreatedAt, v))
}

// TeamIDEQ applies the EQ predicate on the "team_id" field.
func TeamIDEQ(v int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldEQ(FieldTeamID, v))
}

// TeamIDNEQ applies the NEQ predicate on the "team_id" field.
func TeamIDNEQ(v int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldNEQ(FieldTeamID, v))
}

// TeamIDIn applies the In predicate on the "team_id" field.
func TeamIDIn(vs ...int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldIn(FieldTeamID, vs...))
}

// TeamIDNotIn applies the NotIn predicate on the "team_id" field.
func TeamIDNotIn(vs ...int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldNotIn(FieldTeamID, vs...))
}

// OperatorIDEQ applies the EQ predicate on the "operator_id" field.
func OperatorIDEQ(v int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldEQ(FieldOperatorID, v))
}

// OperatorIDNEQ applies the NEQ predicate on the "operator_id" field.
func OperatorIDNEQ(v int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldNEQ(FieldOperatorID, v))
}

// OperatorIDIn applies the In predicate on the "operator_id" field.
func OperatorIDIn(vs ...int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldIn(FieldOperatorID, vs...))
}

// OperatorIDNotIn applies the NotIn predicate on the "operator_id" field.
func OperatorIDNotIn(vs ...int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldNotIn(FieldOperatorID, vs...))
}

// OperatorIDGT applies the GT predicate on the "operator_id" field.
func OperatorIDGT(v int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldGT(FieldOperatorID, v))
}

// OperatorIDGTE applies the GTE predicate on the "operator_id" field.
func OperatorIDGTE(v int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldGTE(FieldOperatorID, v))
}

// OperatorIDLT applies the LT predicate on the "operator_id" field.
func OperatorIDLT(v int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldLT(FieldOperatorID, v))
}

// OperatorIDLTE applies the LTE predicate on the "operator_id" field.
func OperatorIDLTE(v int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldLTE(FieldOperatorID, v))
}

// MemberIDEQ applies the EQ predicate on the "member_id" field.
func MemberIDEQ(v int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldEQ(FieldMemberID, v))
}

// MemberIDNEQ applies the NEQ predicate on the "member_id" field.
func MemberIDNEQ(v int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldNEQ(FieldMemberID, v))
}

// MemberIDIn applies the In predicate on the "member_id" field.
func MemberIDIn(vs ...int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldIn(FieldMemberID, vs...))
}

// MemberIDNotIn applies the NotIn predicate on the "member_id" field.
func MemberIDNotIn(vs ...int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldNotIn(FieldMemberID, vs...))
}

// MemberIDGT applies the GT predicate on the "member_id" field.
func MemberIDGT(v int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldGT(FieldMemberID, v))
}

// MemberIDGTE applies the GTE predicate on the "member_id" field.
func MemberIDGTE(v int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldGTE(FieldMemberID, v))
}

// MemberIDLT applies the LT predicate on the "member_id" field.
func MemberIDLT(v int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldLT(FieldMemberID, v))
}

// MemberIDLTE applies the LTE predicate on the "member_id" field.
func MemberIDLTE(v int64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldLTE(FieldMemberID, v))
}

// MemberIDIsNil applies the IsNil predicate on the "member_id" field.
func MemberIDIsNil() predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldIsNull(FieldMemberID))
}

// MemberIDNotNil applies the NotNil predicate on the "member_id" field.
func MemberIDNotNil() predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldNotNull(FieldMemberID))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldContainsFold(FieldAction, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldLTE(FieldAmount, v))
}

// OwnerBalanceBeforeEQ applies the EQ predicate on the "owner_balance_before" field.
func OwnerBalanceBeforeEQ(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldEQ(FieldOwnerBalanceBefore, v))
}

// OwnerBalanceBeforeNEQ applies the NEQ predicate on the "owner_balance_before" field.
func OwnerBalanceBeforeNEQ(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldNEQ(FieldOwnerBalanceBefore, v))
}

// OwnerBalanceBeforeIn applies the In predicate on the "owner_balance_before" field.
func OwnerBalanceBeforeIn(vs ...float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldIn(FieldOwnerBalanceBefore, vs...))
}

// OwnerBalanceBeforeNotIn applies the NotIn predicate on the "owner_balance_before" field.
func OwnerBalanceBeforeNotIn(vs ...float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldNotIn(FieldOwnerBalanceBefore, vs...))
}

// OwnerBalanceBeforeGT applies the GT predicate on the "owner_balance_before" field.
func OwnerBalanceBeforeGT(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldGT(FieldOwnerBalanceBefore, v))
}

// OwnerBalanceBeforeGTE applies the GTE predicate on the "owner_balance_before" field.
func OwnerBalanceBeforeGTE(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldGTE(FieldOwnerBalanceBefore, v))
}

// OwnerBalanceBeforeLT applies the LT predicate on the "owner_balance_before" field.
func OwnerBalanceBeforeLT(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldLT(FieldOwnerBalanceBefore, v))
}

// OwnerBalanceBeforeLTE applies the LTE predicate on the "owner_balance_before" field.
func OwnerBalanceBeforeLTE(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldLTE(FieldOwnerBalanceBefore, v))
}

// OwnerBalanceAfterEQ applies the EQ predicate on the "owner_balance_after" field.
func OwnerBalanceAfterEQ(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldEQ(FieldOwnerBalanceAfter, v))
}

// OwnerBalanceAfterNEQ applies the NEQ predicate on the "owner_balance_after" field.
func OwnerBalanceAfterNEQ(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldNEQ(FieldOwnerBalanceAfter, v))
}

// OwnerBalanceAfterIn applies the In predicate on the "owner_balance_after" field.
func OwnerBalanceAfterIn(vs ...float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldIn(FieldOwnerBalanceAfter, vs...))
}

// OwnerBalanceAfterNotIn applies the NotIn predicate on the "owner_balance_after" field.
func OwnerBalanceAfterNotIn(vs ...float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldNotIn(FieldOwnerBalanceAfter, vs...))
}

// OwnerBalanceAfterGT applies the GT predicate on the "owner_balance_after" field.
func OwnerBalanceAfterGT(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldGT(FieldOwnerBalanceAfter, v))
}

// OwnerBalanceAfterGTE applies the GTE predicate on the "owner_balance_after" field.
func OwnerBalanceAfterGTE(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldGTE(FieldOwnerBalanceAfter, v))
}

// OwnerBalanceAfterLT applies the LT predicate on the "owner_balance_after" field.
func OwnerBalanceAfterLT(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldLT(FieldOwnerBalanceAfter, v))
}

// OwnerBalanceAfterLTE applies the LTE predicate on the "owner_balance_after" field.
func OwnerBalanceAfterLTE(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldLTE(FieldOwnerBalanceAfter, v))
}

// MemberBalanceBeforeEQ applies the EQ predicate on the "member_balance_before" field.
func MemberBalanceBeforeEQ(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldEQ(FieldMemberBalanceBefore, v))
}

// MemberBalanceBeforeNEQ applies the NEQ predicate on the "member_balance_before" field.
func MemberBalanceBeforeNEQ(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldNEQ(FieldMemberBalanceBefore, v))
}

// MemberBalanceBeforeIn applies the In predicate on the "member_balance_before" field.
func MemberBalanceBeforeIn(vs ...float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldIn(FieldMemberBalanceBefore, vs...))
}

// MemberBalanceBeforeNotIn applies the NotIn predicate on the "member_balance_before" field.
func MemberBalanceBeforeNotIn(vs ...float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldNotIn(FieldMemberBalanceBefore, vs...))
}

// MemberBalanceBeforeGT applies the GT predicate on the "member_balance_before" field.
func MemberBalanceBeforeGT(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldGT(FieldMemberBalanceBefore, v))
}

// MemberBalanceBeforeGTE applies the GTE predicate on the "member_balance_before" field.
func MemberBalanceBeforeGTE(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldGTE(FieldMemberBalanceBefore, v))
}

// MemberBalanceBeforeLT applies the LT predicate on the "member_balance_before" field.
func MemberBalanceBeforeLT(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldLT(FieldMemberBalanceBefore, v))
}

// MemberBalanceBeforeLTE applies the LTE predicate on the "member_balance_before" field.
func MemberBalanceBeforeLTE(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldLTE(FieldMemberBalanceBefore, v))
}

// MemberBalanceBeforeIsNil applies the IsNil predicate on the "member_balance_before" field.
func MemberBalanceBeforeIsNil() predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldIsNull(FieldMemberBalanceBefore))
}

// MemberBalanceBeforeNotNil applies the NotNil predicate on the "member_balance_before" field.
func MemberBalanceBeforeNotNil() predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldNotNull(FieldMemberBalanceBefore))
}

// MemberBalanceAfterEQ applies the EQ predicate on the "member_balance_after" field.
func MemberBalanceAfterEQ(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldEQ(FieldMemberBalanceAfter, v))
}

// MemberBalanceAfterNEQ applies the NEQ predicate on the "member_balance_after" field.
func MemberBalanceAfterNEQ(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldNEQ(FieldMemberBalanceAfter, v))
}

// MemberBalanceAfterIn applies the In predicate on the "member_balance_after" field.
func MemberBalanceAfterIn(vs ...float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldIn(FieldMemberBalanceAfter, vs...))
}

// MemberBalanceAfterNotIn applies the NotIn predicate on the "member_balance_after" field.
func MemberBalanceAfterNotIn(vs ...float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldNotIn(FieldMemberBalanceAfter, vs...))
}

// MemberBalanceAfterGT applies the GT predicate on the "member_balance_after" field.
func MemberBalanceAfterGT(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldGT(FieldMemberBalanceAfter, v))
}

// MemberBalanceAfterGTE applies the GTE predicate on the "member_balance_after" field.
func MemberBalanceAfterGTE(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldGTE(FieldMemberBalanceAfter, v))
}

// MemberBalanceAfterLT applies the LT predicate on the "member_balance_after" field.
func MemberBalanceAfterLT(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldLT(FieldMemberBalanceAfter, v))
}

// MemberBalanceAfterLTE applies the LTE predicate on the "member_balance_after" field.
func MemberBalanceAfterLTE(v float64) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldLTE(FieldMemberBalanceAfter, v))
}

// MemberBalanceAfterIsNil applies the IsNil predicate on the "member_balance_after" field.
func MemberBalanceAfterIsNil() predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldIsNull(FieldMemberBalanceAfter))
}

// MemberBalanceAfterNotNil applies the NotNil predicate on the "member_balance_after" field.
func MemberBalanceAfterNotNil() predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldNotNull(FieldMemberBalanceAfter))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldHasSuffix(FieldNote, v))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldContainsFold(FieldNote, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.FieldLTE(FieldCreatedAt, v))
}

// HasTeam applies the HasEdge predicate on the "team" edge.
func HasTeam() predicate.TeamTransaction {
	return predicate.TeamTransaction(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TeamTable, TeamColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamWith applies the HasEdge predicate on the "team" edge with a given conditions (other predicates).
func HasTeamWith(preds ...predicate.Team) predicate.TeamTransaction {
	return predicate.TeamTransaction(func(s *sql.Selector) {
		step := newTeamStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TeamTransaction) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TeamTransaction) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TeamTransaction) predicate.TeamTransaction {
	return predicate.TeamTransaction(sql.NotPredicates(p))
}
